
<div
	id="banner" class="grid_12 border_light">

	<!-- Starting the search -->
		<?php echo $this->search( array() );?>
	<!-- End of search -->

	<!-- Random_posts is the wrapper for all the images in the cycle -->
	<div id="random_posts">

		<!-- this is the first cycle -->
		<div>

			<div class="random_image">
				<a title="post title" href="#"><img
					src="/assets/images/random_listing.jpg" alt="post title" /> </a>
			</div>

			<div class="description">
				<h2>The Priory</h2>
				<p>30 Deanery Close, Sudbury, Suffolk, CO10 1GE</p>
				<p class="random_price">&pound;250,000</p>
			</div>
		</div>
		<!-- end first cylce -->

		<div>
			<!-- this is the second cycle -->

			<div class="random_image">
				<a title="post title" href="#"><img
					src="/assets/images/random_listing2.jpg" alt="post title" /> </a>
			</div>

			<div class="description">
				<h2>The Mansion</h2>
				<p>4 Amazing Street, Best, Cool, CO89 980</p>
				<p class="random_price">&pound;999,000</p>
			</div>
		</div>
		<!-- end of second cycle -->

		<div>
			<!-- this is the third cycle -->

			<div class="random_image">
				<a title="post title" href="#"><img
					src="/assets/images/random_listing3.jpg" alt="post title" /> </a>
			</div>

			<div class="description">
				<h2>Pinecroft</h2>
				<p>4 Pinecroft Rise, Sudbury, Suffolk, CO10 7PA</p>
				<p class="random_price">&pound;100,999</p>
			</div>
		</div>
		<!-- end of third cycle -->

		<div>
			<!-- this is the fourth cycle -->

			<div class="random_image">
				<a title="post title" href="#"><img
					src="/assets/images/random_listing4.jpg" alt="post title" /> </a>
			</div>

			<div class="description">
				<h2>100a Ballingdon</h2>
				<p>100a Ballingdon Street, Cornard, West Sussex, TW8 298</p>
				<p class="random_price">&pound;120,023</p>
			</div>
		</div>
		<!-- end of fourth cycle -->

		<!-- repeat the above here to add more cycles -->
	</div>
	<!-- random posts-->
</div>
