
<div id="right_side">

	<div class="result">

		<div id="description">

			<h1>Contact Us</h1>

			<form action="#" method="get">

				<label>Forename:</label> <input name="name" type="text" /> <label>Surname:</label>
				<input name="name" type="text" /> <label>Message:</label>
				<textarea name="message" cols="" rows="10">Type your message here....</textarea>

				<input class="submit colour_darkest" name="" type="submit" />

			</form>

		</div>
		<!--description-->

		<div class="clear">&amp;</div>
		<!--result end-->
	</div>
	<!--result-->

</div>
<!--right side-->
