<!-- The banner -->

<!--banner-->
<?php echo $this->render('site/_banner.phtml'); ?>
<div class="clear"></div>
<!-- Banner finished -->

<div class="spacer">&nbsp;</div>

<!-- This displays the 4 properties using a list -->
<div id="listing" class="grid_8 alpha omega">

	<ul>
		<!-- The first property -->
		<!-- The onmouseover and onmouseout attributes create the hover effect -->
		<li
			onmouseover="this.className='grid_4 border_medium background_lightest hover'"
			onmouseout="this.className='grid_4 border_light background_white'"
			class="grid_4 border_light background_white"><a class="link"
			title="This property has &lt;strong&gt;5&lt;/strong&gt; images"
			href="/app/site/view/"> <!-- The propert image --> <span class="listing_image"><img
					src="/assets/images/temp.jpg" alt="test pic" /> </span> <!-- the property text -->
				<span class="text_wrap"> <span class="city">Sudbury, Suffolk<br /> </span>
					<span class="address">30 Deanery Close<br /> </span> <span
					class="price colour_dark">&pound;250,000<br /> </span> <span
					class="icon_number">6</span> <span class="icon"><img width="18"
						height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /> </span>
					<span class="icon_number">2</span> <span class="icon"><img
						width="18" height="14" src="/assets/images/icon_shower.png"
						alt="Bathrooms" /> </span> <span class="icon_number">2</span> <span
					class="icon"><img width="18" height="14"
						src="/assets/images/icon_car.png" alt="Garages" /> </span> </span>
		</a>
		</li>

		<!-- The second property -->
		<li
			onmouseover="this.className='grid_4 border_medium background_lightest hover'"
			onmouseout="this.className='grid_4 border_light background_white'"
			class="grid_4 border_light background_white"><a class="link"
			title="This property has &lt;strong&gt;15&lt;/strong&gt; images"
			href="/app/site/view/"> <span class="listing_image"><img
					src="/assets/images/temp.jpg" alt="test pic" /> </span> <span
				class="text_wrap"> <span class="city">Sudbury, Suffolk<br /> </span>
					<span class="address">30 Deanery Close<br /> </span> <span
					class="price colour_dark">&pound;250,000<br /> </span> <span
					class="icon_number">6</span> <span class="icon"><img width="18"
						height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /> </span>
					<span class="icon_number">2</span> <span class="icon"><img
						width="18" height="14" src="/assets/images/icon_shower.png"
						alt="Bathrooms" /> </span> <span class="icon_number">2</span> <span
					class="icon"><img width="18" height="14"
						src="/assets/images/icon_car.png" alt="Garages" /> </span> </span>
		</a>
		</li>

		<!-- The third property -->
		<li
			onmouseover="this.className='grid_4 border_medium background_lightest hover'"
			onmouseout="this.className='grid_4 border_light background_white'"
			class="grid_4 border_light background_white"><a class="link"
			title="This property has &lt;strong&gt;2&lt;/strong&gt; images"
			href="/app/site/view/"> <span class="listing_image"><img
					src="/assets/images/temp.jpg" alt="test pic" /> </span> <span
				class="text_wrap"> <span class="city">Sudbury, Suffolk<br /> </span>
					<span class="address">30 Deanery Close<br /> </span> <span
					class="price colour_dark">&pound;250,000<br /> </span> <span
					class="icon_number">6</span> <span class="icon"><img width="18"
						height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /> </span>
					<span class="icon_number">2</span> <span class="icon"><img
						width="18" height="14" src="/assets/images/icon_shower.png"
						alt="Bathrooms" /> </span> <span class="icon_number">2</span> <span
					class="icon"><img width="18" height="14"
						src="/assets/images/icon_car.png" alt="Garages" /> </span> </span>
		</a>
		</li>

		<!-- The fourth property -->
		<li
			onmouseover="this.className='grid_4 border_medium background_lightest hover'"
			onmouseout="this.className='grid_4 border_light background_white'"
			class="grid_4 border_light background_white"><a class="link"
			title="This property has &lt;strong&gt;14&lt;/strong&gt; images"
			href="/app/site/view/"> <span class="listing_image"><img
					src="/assets/images/temp.jpg" alt="test pic" /> </span> <span
				class="text_wrap"> <span class="city">Sudbury, Suffolk<br /> </span>
					<span class="address">30 Deanery Close<br /> </span> <span
					class="price colour_dark">&pound;250,000<br /> </span> <span
					class="icon_number">6</span> <span class="icon"><img width="18"
						height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /> </span>
					<span class="icon_number">2</span> <span class="icon"><img
						width="18" height="14" src="/assets/images/icon_shower.png"
						alt="Bathrooms" /> </span> <span class="icon_number">2</span> <span
					class="icon"><img width="18" height="14"
						src="/assets/images/icon_car.png" alt="Garages" /> </span> </span>
		</a>
		</li>

		<!-- Add more propertys here -->
	</ul>
</div>

<!-- The welcome text -->
<div id="welcome" class="grid_4 omega" style="width: 300px;">
	<h2>Buying a Home</h2>
	<p>Nam velit pede, pretium eget, dapibus accumsan, suscipit non,
		tortor. Pellentesque justo. Nam lacinia interdum lacus. Nunc gravida
		blandit est. Mauris vulputate semper dolor.</p>

	<p>Vivamus et odio. Nulla at leo ac pede aliquam dapibus. Donec
		vestibulum varius ligula. Vivamus et odio.</p>

	<p>Donec vestibulum varius ligula. Vivamus et odio. Nulla at leo ac
		pede aliquam dapibus.</p>
</div>


