<div class="container_12">

	<div id="wrap">
		<!-- This is to fix postitioning bug in IE6 -->
		<div id="header_shine"></div>
	</div>

	<div class="grid_12 spacer">&nbsp;</div>
	<div class="grid_12 spacer">&nbsp;</div>

	<!-- nav -->

	<div class="clear"></div>
	<!-- Header finished -->

	<div class="spacer">&nbsp;</div>


	<div class="grid_12 border_light" id="holder">
		<div id="sidebar_image">

			<div id="sidebar">
				<h3>News Categories</h3>
				<ul>
					<li class="background_light colour_dark"><a
						class="border_bottom_lightest" href="#">Category 1 <span
							class="black"></span>
					</a>
					</li>
					<li class="background_light colour_dark"><a
						class="border_bottom_lightest" href="#">Category 2 <span
							class="black"></span>
					</a>
					</li>
					<li class="background_light colour_dark"><a
						class="border_bottom_lightest" href="#">Category 3 <span
							class="black"></span>
					</a>
					</li>
					<li class="background_light colour_dark"><a
						class="border_bottom_lightest" href="#">Category 4 <span
							class="black"></span>
					</a>
					</li>
				</ul>
				<div class="clear">&amp;</div>
				<!--sidebar end-->
			</div>
			<!--sidebar-->

			<div id="right_side">


				<div class="result border_light">

					<div class="result_image">
						<a class="background_light border_medium"
							onmouseover="this.className='background_lightest border_light'"
							onmouseout="this.className='background_light border_medium'"
							href="view"><img src="/assets/images/temp.jpg"
							alt="temp" />
						</a>
					</div>

					<div class="result_text">

						<h2 class="colour_dark">
							<a href="view">The Ultimate Real Estate Theme</a>
						</h2>
						<br />

						<p>
							Lorem Ipsum is simply dummy text of the printing and typesetting
							industry. Lorem Ipsum has been the industry's standard dummy text
							ever since the 1500s, when an... <a href="view">Continue
								reading...</a>
						</p>
						<p class="links">
							Category: <a href="#">category 1</a>, <a href="#">category 2</a>,
							<a href="#">category 3</a>
						</p>

					</div>

					<div class="clear">&amp;</div>
					<!--result end-->
				</div>
				<!--result-->


				<div class="result border_light">

					<div class="result_image">
						<a class="background_light border_medium"
							onmouseover="this.className='background_lightest border_light'"
							onmouseout="this.className='background_light border_medium'"
							href="view"><img src="/assets/images/temp.jpg"
							alt="temp" />
						</a>
					</div>

					<div class="result_text">

						<h2 class="colour_dark">
							<a href="view">Sales, Sales, Sales</a>
						</h2>
						<br />

						<p>
							Lorem Ipsum is simply dummy text of the printing and typesetting
							industry. Lorem Ipsum has been the industry's standard dummy text
							ever since the 1500s, when an... <a href="view">Continue
								reading...</a>
						</p>
						<p class="links">
							Category: <a href="#">category 1</a>, <a href="#">category 2</a>,
							<a href="#">category 3</a>
						</p>

					</div>

					<div class="clear">&amp;</div>
					<!--result end-->
				</div>
				<!--result-->


				<div class="result border_light">

					<div class="result_image">
						<a class="background_light border_medium"
							onmouseover="this.className='background_lightest border_light'"
							onmouseout="this.className='background_light border_medium'"
							href="view"><img src="/assets/images/temp.jpg"
							alt="temp" />
						</a>
					</div>

					<div class="result_text">

						<h2 class="colour_dark">
							<a href="view">Winners of Best Estate Agent 2009</a>
						</h2>
						<br />

						<p>
							Lorem Ipsum is simply dummy text of the printing and typesetting
							industry. Lorem Ipsum has been the industry's standard dummy text
							ever since the 1500s, when an... <a href="view">Continue
								reading...</a>
						</p>
						<p class="links">
							Category: <a href="#">category 1</a>, <a href="#">category 2</a>,
							<a href="#">category 3</a>
						</p>

					</div>

					<div class="clear">&amp;</div>
					<!--result end-->
				</div>
				<!--result-->

				<div class="result border_light">

					<div class="result_image">
						<a class="background_light border_medium"
							onmouseover="this.className='background_lightest border_light'"
							onmouseout="this.className='background_light border_medium'"
							href="view"><img src="/assets/images/temp.jpg"
							alt="temp" />
						</a>
					</div>

					<div class="result_text">

						<h2 class="colour_dark">
							<a href="view">Website hits gone throguh the roof!</a>
						</h2>
						<br />

						<p>
							Lorem Ipsum is simply dummy text of the printing and typesetting
							industry. Lorem Ipsum has been the industry's standard dummy text
							ever since the 1500s, when an... <a href="view">Continue
								reading...</a>
						</p>
						<p class="links">
							Category: <a href="#">category 1</a>, <a href="#">category 2</a>,
							<a href="#">category 3</a>
						</p>

					</div>

					<div class="clear">&amp;</div>
					<!--result end-->
				</div>
				<!--result-->

				<div class="result border_light">

					<div class="result_image">
						<a class="background_light border_medium"
							onmouseover="this.className='background_lightest border_light'"
							onmouseout="this.className='background_light border_medium'"
							href="view"><img src="/assets/images/temp.jpg"
							alt="temp" />
						</a>
					</div>

					<div class="result_text">

						<h2 class="colour_dark">
							<a href="view">This theme author is cool</a>
						</h2>
						<br />

						<p>
							Lorem Ipsum is simply dummy text of the printing and typesetting
							industry. Lorem Ipsum has been the industry's standard dummy text
							ever since the 1500s, when an... <a href="view">Continue
								reading...</a>
						</p>
						<p class="links">
							Category: <a href="#">category 1</a>, <a href="#">category 2</a>,
							<a href="#">category 3</a>
						</p>

					</div>

					<div class="clear">&amp;</div>
					<!--result end-->
				</div>
				<!--result-->

				<div class="result border_light">

					<div class="result_image">
						<a class="background_light border_medium"
							onmouseover="this.className='background_lightest border_light'"
							onmouseout="this.className='background_light border_medium'"
							href="view"><img src="/assets/images/temp.jpg"
							alt="temp" />
						</a>
					</div>

					<div class="result_text">

						<h2 class="colour_dark">
							<a href="view">How to make $$$ on lettings</a>
						</h2>
						<br />

						<p>
							Lorem Ipsum is simply dummy text of the printing and typesetting
							industry. Lorem Ipsum has been the industry's standard dummy text
							ever since the 1500s, when an... <a href="view">Continue
								reading...</a>
						</p>
						<p class="links">
							Category: <a href="#">category 1</a>, <a href="#">category 2</a>,
							<a href="#">category 3</a>
						</p>

					</div>

					<div class="clear">&amp;</div>
					<!--result end-->
				</div>
				<!--result-->

				<div class="result border_light">

					<div class="result_image">
						<a class="background_light border_medium"
							onmouseover="this.className='background_lightest border_light'"
							onmouseout="this.className='background_light border_medium'"
							href="view"><img src="/assets/images/temp.jpg"
							alt="temp" />
						</a>
					</div>

					<div class="result_text">

						<h2 class="colour_dark">
							<a href="view">Stop... Hammer time</a>
						</h2>
						<br />

						<p>
							Lorem Ipsum is simply dummy text of the printing and typesetting
							industry. Lorem Ipsum has been the industry's standard dummy text
							ever since the 1500s, when an... <a href="view">Continue
								reading...</a>
						</p>
						<p class="links">
							Category: <a href="#">category 1</a>, <a href="#">category 2</a>,
							<a href="#">category 3</a>
						</p>

					</div>

					<div class="clear">&amp;</div>
					<!--result end-->
				</div>
				<!--result-->

			</div>
			<!--right side-->

			<div class="clear">&amp;</div>
			<!--sidebar image end-->
		</div>
		<!--sidebar_image-->

	</div>
	<!--holder-->

	<div class="clear"></div>
	<!-- holder finished -->
</div>
<!-- container_12 -->
