<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Realist - The Ultimate Real Estate Theme</title>

<link href="/css/960.css" rel="stylesheet" type="text/css" />
<link href="/css/reset.css" rel="stylesheet" type="text/css" />
<link href="/css/text.css" rel="stylesheet" type="text/css" />
<link href="/css/style.css" rel="stylesheet" type="text/css" />

<!-- These are all the different colour variations. To create your own please see the help file -->

<!--<link href="/css/style_rouge.css" rel="stylesheet" type="text/css" />-->
<!--<link href="/css/style_forest.css" rel="stylesheet" type="text/css" />-->
<!--<link href="/css/style_lake.css" rel="stylesheet" type="text/css" />-->
<!--<link href="/css/style_fame.css" rel="stylesheet" type="text/css" />-->
<!--<link href="/css/style_old.css" rel="stylesheet" type="text/css" />-->

<!-- Loads jquery as well as jQuery Tools -->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script> 
<script type="text/javascript" src="/js/jquery.tools.min.js"></script> 
<script type="text/javascript" src="/js/pngfix/jquery.pngFix.js"></script> 
<script type="text/javascript" src="/js/jquery.cycle.all.min.js"></script>
<script type="text/javascript" src="/js/jquery.qtip.min.js"></script> 
<script type="text/javascript" src="/js/superfish.js"></script>
<script type="text/javascript" src="/js/inc.js"></script> 

</head>

<body>

	<div class="container_12">
    	
        <div id="wrap"><!-- This is to fix postitioning bug in IE6 -->
        <div id="header_shine"></div>
        </div>
        
        <div class="grid_12 spacer">&nbsp;</div>
        
        <div class="grid_4 logo">
        
        	<h1>Realist - The Ultimate Real Estate Theme </h1>
            
        </div>
        
        
        <div class="grid_8 colour_darkest" id="phone_number">
        
        	<img src="/assets/images/phone_icon.jpg" alt=" " />01787 123456<br />
            <span class="tagline">Call for free now</span>
        
        </div>
        
   		<div class="grid_12 spacer">&nbsp;</div>
        
        <div class="grid_12" id="nav">
        
        	<ul class="sf-menu">
            
              <li><a title="" href="index.html">Home</a></li>
              <li><a title="" href="search_results.html">Buying</a>
                
                	<ul>
                    	<li><a title="" href="page.html">Dropdown</a></li>
                        <li><a title="" href="page.html">Dropdown</a></li>
                        <li><a title="" href="page.html">Dropdown</a></li>
                        <li><a title="" href="page.html">Dropdown</a></li>
                        <li><a title="" href="page.html">An Example -</a>
                        	<ul>
                                <li><a title="" href="page.html">Another</a></li>
                                <li><a title="" href="page.html">Another</a></li>
                                <li><a title="" href="page.html">Example -</a>
                                	<ul>
                                        <li><a title="" href="page.html">Oh Look</a></li>
                                        <li><a title="" href="page.html">It's another!</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
              </li>
              <li><a title="" href="search_results.html">Renting</a></li>
              <li><a title="" href="search_results.html">Selling</a>
              
              		<ul>
                    	<li><a title="" href="page.html">Hello</a></li>
                        <li><a title="" href="page.html">how's you?</a></li>
                    </ul>
                    
              </li>
              <li><a title="" href="news.html">News</a></li>
              <li><a title="" href="contact.html">Contact</a></li>
                
          </ul>
           
        </div> <!-- nav -->
        
    <div class="clear"></div> <!-- Header finished -->
    
    <div class="spacer">&nbsp;</div>
    
    
    <div class="grid_12 border_light" id="holder">
    
    	<!-- The sidebar image gets repeated all the way down the page -->
    	<div id="sidebar_image">
    	
        <!-- This is now called sidebar, not search! -->
   		<div id="sidebar">
        
            <h3>Change Criteria</h3>
            <form class="expose" action="#" method="get" name="search">
        
        <div class="row">
        	<label>Location</label>
        </div>
        
        <div class="row">
            <div class="box large border_light">
            	<select class="large" name="location">
                	 <optgroup label="England">
                     <option>Anywhere, I don't mind</option>
                     <option>Bedfordshire</option>
                     <option>Berkshire</option>
                     <option>Bristol</option>
                     <option>Buckinghamshire</option>
                     <option>Cambridgeshire</option>
                     <option>Cheshire</option>
                     <option>City of London</option>
                     <option>Cornwall</option>
                     <option>Cumbria</option>
                     <option>Derbyshire</option>
                     <option>Devon</option>
                     <option>Dorset</option>
                     <option>Durham</option>
                     <option>East Riding of Yorkshire</option>
                     <option>East Sussex</option>
                     <option>Essex</option>
                     <option>Gloucestershire</option>
                     <option>Greater London</option>
                     <option>Greater Manchester</option>
                     <option>Hampshire</option>
                     <option>Herefordshire</option>
                     <option>Hertfordshire</option>
                     <option>Isle of Wight</option>
                     <option>Kent</option>
                     <option>Lancashire</option>
                     <option>Leicestershire</option>
                     <option>Lincolnshire</option>
                     <option>Merseyside</option>
                     <option>Norfolk</option>
                     <option>North Yorkshire</option>
                     <option>Northamptonshire</option>
                     <option>Northumberland</option>
                     <option>Nottinghamshire</option>
                     <option>Oxfordshire</option>
                     <option>Rutland</option>
                     <option>Shropshire</option>
                     <option>Somerset</option>
                     <option>South Yorkshire</option>
                     <option>Staffordshire</option>
                     <option>Suffolk</option>
                     <option>Surrey</option>
                     <option>Tyne and Wear</option>
                     <option>Warwickshire</option>
                     <option>West Midlands</option>
                     <option>West Sussex</option>
                     <option>West Yorkshire</option>
                     <option>Wiltshire</option>
                     <option>Worcestershire</option>
                     </optgroup>
                     <optgroup label="Wales">
                     <option>Anglesey</option>
                     <option>Brecknockshire</option>
                     <option>Caernarfonshire</option>
                     <option>Carmarthenshire</option>
                     <option>Cardiganshire</option>
                     <option>Denbighshire</option>
                     <option>Flintshire</option>
                     <option>Glamorgan</option>
                     <option>Merioneth</option>
                     <option>Monmouthshire</option>
                     <option>Montgomeryshire</option>
                     <option>Pembrokeshire</option>
                     <option>Radnorshire</option>
                     </optgroup>
                     <optgroup label="Scotland">
                     <option>Aberdeenshire</option>
                     <option>Angus</option>
                     <option>Argyllshire</option>
                     <option>Ayrshire</option>
                     <option>Banffshire</option>
                     <option>Berwickshire</option>
                     <option>Buteshire</option>
                     <option>Cromartyshire</option>
                     <option>Caithness</option>
                     <option>Clackmannanshire</option>
                     <option>Dumfriesshire</option>
                     <option>Dunbartonshire</option>
                     <option>East Lothian</option>
                     <option>Fife</option>
                     <option>Inverness-shire</option>
                     <option>Kincardineshire</option>
                     <option>Kinross</option>
                     <option>Kirkcudbrightshire</option>
                     <option>Lanarkshire</option>
                     <option>Midlothian</option>
                     <option>Morayshire</option>
                     <option>Nairnshire</option>
                     <option>Orkney</option>
                     <option>Peeblesshire</option>
                     <option>Perthshire</option>
                     <option>Renfrewshire</option>
                     <option>Ross-shire</option>
                     <option>Roxburghshire</option>
                     <option>Selkirkshire</option>
                     <option>Shetland</option>
                     <option>Stirlingshire</option>
                     <option>Sutherland</option>
                     <option>West Lothian</option>
                     <option>Wigtownshire</option>
                     </optgroup>
                     <optgroup label="Northern Ireland">
                     <option>Antrim</option>
                     <option>Armagh</option>
                     <option>Down</option>
                     <option>Fermanagh</option>
                    <option>Londonderry</option>
                    <option>Tyrone</option>
                    </optgroup>
                </select>
            </div>
		</div>
        
        <div class="row">
            <label>Bedrooms</label>
            <label>Buying Price</label>
            <label>Renting Price</label>
        </div>
        
       <div class="row">
            <div class="box small border_light">
            	<select class="small" name="beds">
                	<option value="any">Any</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5+</option>
                </select>
            </div>
          <div class="box medium border_light">
           	  <select class="medium" name="min">
                	<option value="any">Any</option>
                    <option value="100000">&pound;100,000+</option>
                    <option value="200000">&pound;200,000+</option>
                    <option value="300000">&pound;300,000+</option>
                    <option value="400000">&pound;400,000+</option>
                    <option value="500000">&pound;500,000+</option>
                </select>
          </div>
            
            <div class="box medium border_light">
            	<select class="medium" name="max">
                	<option value="any">Any</option>
                    <option value="100000">&pound;400+</option>
                    <option value="200000">&pound;600+</option>
                    <option value="300000">&pound;800+</option>
                    <option value="400000">&pound;1000+</option>
            </select>
          </div>
		</div>
        
       <div class="row">
        	<label>Renting or Buying</label>
        </div>
        
        <div class="row">
            <div class="box medium2 border_light">
            	<select class="medium2" name="date">
                	<option value="any">Any, I don't mind</option>
                    <option value="rent">I'm looking to rent</option>
                    <option value="buy">I'm looking to buy</option>
                </select>
            </div>
            
            <div class="left">
          	  <input id="submit" type='image' src='/assets/images/search_btn.jpg' onmouseover="this.src='/assets/images/search_btn_hover.jpg'" onmouseout="this.src='/assets/images/search_btn.jpg'"/>
            </div>
		</div>
        <div class="clear"></div>
        </form>
        
        <!-- Sidebar headers should all be H3's -->
        <h3>Search by Category</h3>
        
        <!-- The sidebar list with H4 headings -->
        <!-- first list -->
        <h4 class="background_medium colour_darkest">Property Type:</h4>
        <ul>
        	<li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Houses <span class="black">(600)</span></a>
            	<ul>
                    <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Detached Houses <span class="black">(200)</span></a></li>
                    <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Semi-detached Houses <span class="black">(300)</span></a></li>
                    <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Terraced Houses <span class="black">(100)</span></a>
                    </li>
                </ul>
            </li>
            
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Flats / Apartments <span class="black">(52)</span></a></li>
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Bungalows <span class="black">(6)</span></a></li>
        </ul>
        
        <!-- second list -->
        <h4 class="background_medium colour_darkest">Furnishing:</h4>
        <ul>
        	<li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Furnished <span class="black">(1548)</span></a></li>
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Part Furnished <span class="black">(250)</span></a></li>
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Unfurnished <span class="black">(254)</span></a></li>
        </ul>
        
        <!-- third list -->
        <h4 class="background_medium colour_darkest">Type:</h4>
        <ul>
        	<li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Buying <span class="black">(1548)</span></a></li>
        	<li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Long Term Let <span class="black">(1548)</span></a></li>
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Short Term Let <span class="black">(250)</span></a></li>
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">House / Flat Share <span class="black">(254)</span></a></li>
        </ul>
        
        <!-- fourth list -->
        <h4 class="background_medium colour_darkest">Outside Space:</h4>
        <ul>
        	<li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Garden <span class="black">(1548)</span></a></li>
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Parking <span class="black">(250)</span></a></li>
        </ul>
        
        <!-- fith list -->
        <h4 class="background_medium colour_darkest">Retirement Properties:</h4>
        <ul>
        	<li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Non-Retirement <span class="black">(1548)</span></a></li>
        </ul>
        
        <!-- add more lists here, following the same patttern -->
        
        <div class="clear">&amp;</div><!--sidebar end-->
        </div><!--sidebar-->
        
        <!-- starting the right side -->
        <div id="right_side">
        	
            <!-- displays the search query -->
        	<div id="search_query" class="border_light background_lightest">
    
            <p>Your Search: <span class="black">2+ Bedroom</span> properties to <span class="black">rent</span> located in <span class="black">Suffolk</span> for <span class="black">£600+</span> per month</p>
            
            </div><!--search_query-->
            
            <!-- display the results -->
            <!-- first result -->
            <div class="result border_light">
            	
                <!-- property image -->
                <div title="This property has &lt;strong&gt;10&lt;/strong&gt; images" class="result_image">
                    <a class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="single.html"><img src="/assets/images/temp.jpg" alt="temp" /></a>
                </div>
                
                <!-- property text -->
                <div class="result_text">
                
                	<!-- the price -->
                    <h2 class="colour_dark">&pound;750/month</h2>
                    
                    <!-- details with icons -->
                    <div class="details">
                    <span class="icon_number">3</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /></span>
                    <span class="icon_number">2</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_shower.png" alt="Bathrooms" /></span>
                    <span class="icon_number">1</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_car.png" alt="Garages" /></span>
                    </div>
                    
                    <!-- property facts -->
                    <h1>3 Bedroom house to rent<br /><span class="text_small">Sudbury, Suffolk</span></h1>
                    
                    <!-- small description -->
                    <p>Beautiful Executive 3 storey, 3 bedroom househouse in elite area, comprising of fully fitted kitchen/diner &amp; appliances, lounge, 6 ensuites, family bathroom.</p>
                    <p class="links"><a href="single.html">More details and 10 photos</a> | <a  href="single.html">Request a viewing</a></p>
                    
                </div>
                
            <div class="clear">&amp;</div><!--result end-->
        	</div><!--result-->
            
            <!-- second result and so on... -->
            <div class="result border_light">
            
                <div title="This property has &lt;strong&gt;10&lt;/strong&gt; images" class="result_image">
                    <a class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="#"><img src="/assets/images/temp.jpg" alt="temp" /></a>
                </div>
                
                <div class="result_text">
                
                    <h2 class="colour_dark">&pound;158,999</h2>
                    
                    <div class="details">
                    <span class="icon_number">1</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /></span>
                    <span class="icon_number">1</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_shower.png" alt="Bathrooms" /></span>
                    <span class="icon_number">0</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_car.png" alt="Garages" /></span>
                    </div>
                    
                    <h1>1 Bedroom flat to buy<br /><span class="text_small">Sudbury, Suffolk</span></h1>
                    
                    <p>Beautiful Executive 3 storey, 3 bedroom househouse in elite area, comprising of fully fitted kitchen/diner &amp; appliances, lounge, 6 ensuites, family bathroom.</p>
                    <p class="links"><a href="single.html">More details and 10 photos</a> | <a  href="single.html">Request a viewing</a></p>
                    
                </div>
                
            <div class="clear">&amp;</div><!--result end-->
        	</div><!--result-->
            
            <div class="result border_light">
            
                <div title="This property has &lt;strong&gt;10&lt;/strong&gt; images" class="result_image">
                    <a class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="#"><img src="/assets/images/temp.jpg" alt="temp" /></a>
                </div>
                
                <div class="result_text">
                
                    <h2 class="colour_dark">&pound;250,000</h2>
                    
                    <div class="details">
                    <span class="icon_number">3</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /></span>
                    <span class="icon_number">2</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_shower.png" alt="Bathrooms" /></span>
                    <span class="icon_number">1</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_car.png" alt="Garages" /></span>
                    </div>
                    
                    <h1>3 Bedroom house to buy<br /><span class="text_small">Sudbury, Suffolk</span></h1>
                    
                    <p>Beautiful Executive 3 storey, 3 bedroom househouse in elite area, comprising of fully fitted kitchen/diner &amp; appliances, lounge, 6 ensuites, family bathroom.</p>
                    <p class="links"><a href="single.html">More details and 10 photos</a> | <a  href="single.html">Request a viewing</a></p>
                    
                </div>
                
            <div class="clear">&amp;</div><!--result end-->
        	</div><!--result-->
            
            <div class="result border_light">
            
                <div title="This property has &lt;strong&gt;10&lt;/strong&gt; images" class="result_image">
                    <a class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="#"><img src="/assets/images/temp.jpg" alt="temp" /></a>
                </div>
                
                <div class="result_text">
                
                    <h2 class="colour_dark">&pound;100,000,000</h2>
                    
                    <div class="details">
                    <span class="icon_number">9</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /></span>
                    <span class="icon_number">5</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_shower.png" alt="Bathrooms" /></span>
                    <span class="icon_number">3</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_car.png" alt="Garages" /></span>
                    </div>
                    
                    <h1>9 Bedroom house to buy<br /><span class="text_small">Sudbury, Suffolk</span></h1>
                    
                    <p>Beautiful Executive 3 storey, 3 bedroom househouse in elite area, comprising of fully fitted kitchen/diner &amp; appliances, lounge, 6 ensuites, family bathroom.</p>
                    <p class="links"><a href="single.html">More details and 10 photos</a> | <a  href="single.html">Request a viewing</a></p>
                    
                </div>
                
            <div class="clear">&amp;</div><!--result end-->
        	</div><!--result-->
            
            <div class="result border_light">
            
                <div title="This property has &lt;strong&gt;10&lt;/strong&gt; images" class="result_image">
                    <a class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="#"><img src="/assets/images/temp.jpg" alt="temp" /></a>
                </div>
                
                <div class="result_text">
                
                    <h2 class="colour_dark">&pound;98,000</h2>
                    
                    <div class="details">
                    <span class="icon_number">1</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /></span>
                    <span class="icon_number">1</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_shower.png" alt="Bathrooms" /></span>
                    <span class="icon_number">0</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_car.png" alt="Garages" /></span>
                    </div>
                    
                    <h1>1 Bedroom house to buy<br /><span class="text_small">Sudbury, Suffolk</span></h1>
                    
                    <p>Beautiful Executive 3 storey, 3 bedroom househouse in elite area, comprising of fully fitted kitchen/diner &amp; appliances, lounge, 6 ensuites, family bathroom.</p>
                  	<p class="links"><a href="single.html">More details and 10 photos</a> | <a href="single.html">Request a viewing</a></p>
                    
                </div>
                
            <div class="clear">&amp;</div><!--result end-->
        	</div><!--result-->
            
            <div class="result border_light">
            
                <div title="This property has &lt;strong&gt;10&lt;/strong&gt; images" class="result_image">
                    <a class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="#"><img src="/assets/images/temp.jpg" alt="temp" /></a>
                </div>
                
                <div class="result_text">
                
                    <h2 class="colour_dark">&pound;780,000</h2>
                    
                    <div class="details">
                    <span class="icon_number">5</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /></span>
                    <span class="icon_number">3</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_shower.png" alt="Bathrooms" /></span>
                    <span class="icon_number">2</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_car.png" alt="Garages" /></span>
                    </div>
                    
                    <h1>5 Bedroom house to buy<br /><span class="text_small">Sudbury, Suffolk</span></h1>
                    
                    <p>Beautiful Executive 3 storey, 3 bedroom househouse in elite area, comprising of fully fitted kitchen/diner &amp; appliances, lounge, 6 ensuites, family bathroom.</p>
                    <p class="links"><a href="single.html">More details and 10 photos</a> | <a  href="single.html">Request a viewing</a></p>
                    
                </div>
                
            <div class="clear">&amp;</div><!--result end-->
        	</div><!--result-->
            
            <div class="result border_light">
            
                <div title="This property has &lt;strong&gt;10&lt;/strong&gt; images" class="result_image">
                    <a class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="#"><img src="/assets/images/temp.jpg" alt="temp" /></a>
                </div>
                
                <div class="result_text">
                
                    <h2 class="colour_dark">&pound;650,495</h2>
                    
                    <div class="details">
                    <span class="icon_number">3</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /></span>
                    <span class="icon_number">2</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_shower.png" alt="Bathrooms" /></span>
                    <span class="icon_number">1</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_car.png" alt="Garages" /></span>
                    </div>
                    
                    <h1>3 Bedroom house to rent<br /><span class="text_small">Sudbury, Suffolk</span></h1>
                    
                    <p>Beautiful Executive 3 storey, 3 bedroom househouse in elite area, comprising of fully fitted kitchen/diner &amp; appliances, lounge, 6 ensuites, family bathroom.</p>
                    <p class="links"><a href="single.html">More details and 10 photos</a> | <a  href="single.html">Request a viewing</a></p>
                    
                </div>
                
            <div class="clear">&amp;</div><!--result end-->
        	</div><!--result-->
            
            <div class="result border_light">
            
                <div title="This property has &lt;strong&gt;10&lt;/strong&gt; images" class="result_image">
                    <a class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="#"><img src="/assets/images/temp.jpg" alt="temp" /></a>
                </div>
                
                <div class="result_text">
                
                    <h2 class="colour_dark">&pound;250,000</h2>
                    
                    <div class="details">
                    <span class="icon_number">3</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /></span>
                    <span class="icon_number">2</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_shower.png" alt="Bathrooms" /></span>
                    <span class="icon_number">1</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_car.png" alt="Garages" /></span>
                    </div>
                    
                    <h1>3 Bedroom house to rent<br /><span class="text_small">Sudbury, Suffolk</span></h1>
                    
                    <p>Beautiful Executive 3 storey, 3 bedroom househouse in elite area, comprising of fully fitted kitchen/diner &amp; appliances, lounge, 6 ensuites, family bathroom.</p>
                    <p class="links"><a href="single.html">More details and 10 photos</a> | <a  href="single.html">Request a viewing</a></p>
                    
                </div>
                
            <div class="clear">&amp;</div><!--result end-->
        	</div><!--result-->
            
            <div class="result border_light">
            
                <div title="This property has &lt;strong&gt;10&lt;/strong&gt; images" class="result_image">
                    <a class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="#"><img src="/assets/images/temp.jpg" alt="temp" /></a>
                </div>
                
                <div class="result_text">
                
                    <h2 class="colour_dark">&pound;250,000</h2>
                    
                    <div class="details">
                    <span class="icon_number">3</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /></span>
                    <span class="icon_number">2</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_shower.png" alt="Bathrooms" /></span>
                    <span class="icon_number">1</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_car.png" alt="Garages" /></span>
                    </div>
                    
                    <h1>3 Bedroom house to rent<br /><span class="text_small">Sudbury, Suffolk</span></h1>
                    
                    <p>Beautiful Executive 3 storey, 3 bedroom househouse in elite area, comprising of fully fitted kitchen/diner &amp; appliances, lounge, 6 ensuites, family bathroom.</p>
                    <p class="links"><a href="single.html">More details and 10 photos</a> | <a  href="single.html">Request a viewing</a></p>
                    
                </div>
                
            <div class="clear">&amp;</div><!--result end-->
        	</div><!--result-->
            
            <div class="result border_light">
            
                <div title="This property has &lt;strong&gt;10&lt;/strong&gt; images" class="result_image">
                    <a class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="#"><img src="/assets/images/temp.jpg" alt="temp" /></a>
                </div>
                
                <div class="result_text">
                
                    <h2 class="colour_dark">&pound;250,000</h2>
                    
                    <div class="details">
                    <span class="icon_number">3</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_bed.png" alt="Bedrooms" /></span>
                    <span class="icon_number">2</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_shower.png" alt="Bathrooms" /></span>
                    <span class="icon_number">1</span>
                    <span class="icon"><img width="18" height="14" src="/assets/images/icon_car.png" alt="Garages" /></span>
                    </div>
                    
                    <h1>3 Bedroom house to rent<br /><span class="text_small">Sudbury, Suffolk</span></h1>
                    
                    <p>Beautiful Executive 3 storey, 3 bedroom househouse in elite area, comprising of fully fitted kitchen/diner &amp; appliances, lounge, 6 ensuites, family bathroom.</p>
                    <p class="links"><a href="single.html">More details and 10 photos</a> | <a  href="single.html">Request a viewing</a></p>
                    
                </div>
                
            <div class="clear">&amp;</div><!--result end-->
        	</div><!--result-->
            
        </div><!--right side-->
        
        <div class="clear">&amp;</div><!--sidebar image end-->
       </div><!--sidebar_image-->
       
    </div><!--holder-->
    
    <div class="clear"></div> <!-- holder finished -->
    
    <div class="spacer">&nbsp;</div>
    
    <div id="footer" class="grid_12">
    
    <p class="left">&copy; 2008-2009 The Ultimate Real Estate Theme</p>
    <p class="right"><a href="#">Terms &amp; Conditions</a> | <a href="#">Contact</a></p>
    
    </div>
    
</div><!-- container_12 -->

</body>

</html>
