<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Realist - The Ultimate Real Estate Theme</title>

<link href="/css/960.css" rel="stylesheet" type="text/css" />
<link href="/css/reset.css" rel="stylesheet" type="text/css" />
<link href="/css/text.css" rel="stylesheet" type="text/css" />
<link href="/css/style.css" rel="stylesheet" type="text/css" />

<!-- These are all the different colour variations. To create your own please see the help file -->

<!--<link href="/css/style_rouge.css" rel="stylesheet" type="text/css" />-->
<!--<link href="/css/style_forest.css" rel="stylesheet" type="text/css" />-->
<!--<link href="/css/style_lake.css" rel="stylesheet" type="text/css" />-->
<!--<link href="/css/style_fame.css" rel="stylesheet" type="text/css" />-->
<!--<link href="/css/style_old.css" rel="stylesheet" type="text/css" />-->

<!-- Loads jquery as well as jQuery Tools -->
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script> 
<script type="text/javascript" src="/js/jquery.tools.min.js"></script> 
<script type="text/javascript" src="/js/pngfix/jquery.pngFix.js"></script> 
<script type="text/javascript" src="/js/jquery.cycle.all.min.js"></script>
<script type="text/javascript" src="/js/jquery.qtip.min.js"></script> 
<script type="text/javascript" src="/js/superfish.js"></script>
<script type="text/javascript" src="/js/inc.js"></script> 

</head>

<body>

	<div class="container_12">
    	
        <div id="wrap"><!-- This is to fix postitioning bug in IE6 -->
        <div id="header_shine"></div>
        </div>
        
        <div class="grid_12 spacer">&nbsp;</div>
        
        <div class="grid_4 logo">
        
        	<h1>Realist - The Ultimate Real Estate Theme </h1>
            
        </div>
        
        
        <div class="grid_8 colour_darkest" id="phone_number">
        
        	<img src="/assets/images/phone_icon.jpg" alt=" " />01787 123456<br />
            <span class="tagline">Call for free now</span>
        
        </div>
        
   		<div class="grid_12 spacer">&nbsp;</div>
        
        <div class="grid_12" id="nav">
        
        	<ul class="sf-menu">
            
              <li><a title="" href="index.html">Home</a></li>
              <li><a title="" href="search_results.html">Buying</a>
                
                	<ul>
                    	<li><a title="" href="page.html">Dropdown</a></li>
                        <li><a title="" href="page.html">Dropdown</a></li>
                        <li><a title="" href="page.html">Dropdown</a></li>
                        <li><a title="" href="page.html">Dropdown</a></li>
                        <li><a title="" href="page.html">An Example -</a>
                        	<ul>
                                <li><a title="" href="page.html">Another</a></li>
                                <li><a title="" href="page.html">Another</a></li>
                                <li><a title="" href="page.html">Example -</a>
                                	<ul>
                                        <li><a title="" href="page.html">Oh Look</a></li>
                                        <li><a title="" href="page.html">It's another!</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
              </li>
              <li><a title="" href="search_results.html">Renting</a></li>
              <li><a title="" href="search_results.html">Selling</a>
              
              		<ul>
                    	<li><a title="" href="page.html">Hello</a></li>
                        <li><a title="" href="page.html">how's you?</a></li>
                    </ul>
                    
              </li>
              <li><a title="" href="news.html">News</a></li>
              <li><a title="" href="contact.html">Contact</a></li>
                
          </ul>
           
        </div> <!-- nav -->
        
    <div class="clear"></div> <!-- Header finished -->
    
    <div class="spacer">&nbsp;</div>
    
    
    <div id="holder" class="grid_12 border_light">
    	<div id="sidebar_image">
    
   		<div id="sidebar">
        
            <h3>Change Criteria</h3>
            <form class="expose" action="#" method="get" name="search">
        
        <div class="row">
        	<label>Location</label>
        </div>
        
        <div class="row">
            <div class="box large border_light">
            	<select class="large" name="location">
                	 <optgroup label="England">
                     <option>Anywhere, I don't mind</option>
                     <option>Bedfordshire</option>
                     <option>Berkshire</option>
                     <option>Bristol</option>
                     <option>Buckinghamshire</option>
                     <option>Cambridgeshire</option>
                     <option>Cheshire</option>
                     <option>City of London</option>
                     <option>Cornwall</option>
                     <option>Cumbria</option>
                     <option>Derbyshire</option>
                     <option>Devon</option>
                     <option>Dorset</option>
                     <option>Durham</option>
                     <option>East Riding of Yorkshire</option>
                     <option>East Sussex</option>
                     <option>Essex</option>
                     <option>Gloucestershire</option>
                     <option>Greater London</option>
                     <option>Greater Manchester</option>
                     <option>Hampshire</option>
                     <option>Herefordshire</option>
                     <option>Hertfordshire</option>
                     <option>Isle of Wight</option>
                     <option>Kent</option>
                     <option>Lancashire</option>
                     <option>Leicestershire</option>
                     <option>Lincolnshire</option>
                     <option>Merseyside</option>
                     <option>Norfolk</option>
                     <option>North Yorkshire</option>
                     <option>Northamptonshire</option>
                     <option>Northumberland</option>
                     <option>Nottinghamshire</option>
                     <option>Oxfordshire</option>
                     <option>Rutland</option>
                     <option>Shropshire</option>
                     <option>Somerset</option>
                     <option>South Yorkshire</option>
                     <option>Staffordshire</option>
                     <option>Suffolk</option>
                     <option>Surrey</option>
                     <option>Tyne and Wear</option>
                     <option>Warwickshire</option>
                     <option>West Midlands</option>
                     <option>West Sussex</option>
                     <option>West Yorkshire</option>
                     <option>Wiltshire</option>
                     <option>Worcestershire</option>
                     </optgroup>
                     <optgroup label="Wales">
                     <option>Anglesey</option>
                     <option>Brecknockshire</option>
                     <option>Caernarfonshire</option>
                     <option>Carmarthenshire</option>
                     <option>Cardiganshire</option>
                     <option>Denbighshire</option>
                     <option>Flintshire</option>
                     <option>Glamorgan</option>
                     <option>Merioneth</option>
                     <option>Monmouthshire</option>
                     <option>Montgomeryshire</option>
                     <option>Pembrokeshire</option>
                     <option>Radnorshire</option>
                     </optgroup>
                     <optgroup label="Scotland">
                     <option>Aberdeenshire</option>
                     <option>Angus</option>
                     <option>Argyllshire</option>
                     <option>Ayrshire</option>
                     <option>Banffshire</option>
                     <option>Berwickshire</option>
                     <option>Buteshire</option>
                     <option>Cromartyshire</option>
                     <option>Caithness</option>
                     <option>Clackmannanshire</option>
                     <option>Dumfriesshire</option>
                     <option>Dunbartonshire</option>
                     <option>East Lothian</option>
                     <option>Fife</option>
                     <option>Inverness-shire</option>
                     <option>Kincardineshire</option>
                     <option>Kinross</option>
                     <option>Kirkcudbrightshire</option>
                     <option>Lanarkshire</option>
                     <option>Midlothian</option>
                     <option>Morayshire</option>
                     <option>Nairnshire</option>
                     <option>Orkney</option>
                     <option>Peeblesshire</option>
                     <option>Perthshire</option>
                     <option>Renfrewshire</option>
                     <option>Ross-shire</option>
                     <option>Roxburghshire</option>
                     <option>Selkirkshire</option>
                     <option>Shetland</option>
                     <option>Stirlingshire</option>
                     <option>Sutherland</option>
                     <option>West Lothian</option>
                     <option>Wigtownshire</option>
                     </optgroup>
                     <optgroup label="Northern Ireland">
                     <option>Antrim</option>
                     <option>Armagh</option>
                     <option>Down</option>
                     <option>Fermanagh</option>
                    <option>Londonderry</option>
                    <option>Tyrone</option>
                    </optgroup>
                </select>
            </div>
		</div>
        
        <div class="row">
            <label>Bedrooms</label>
            <label>Buying Price</label>
            <label>Renting Price</label>
        </div>
        
       <div class="row">
            <div class="box small border_light">
            	<select class="small" name="beds">
                	<option value="any">Any</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5+</option>
                </select>
            </div>
          <div class="box medium border_light">
           	  <select class="medium" name="min">
                	<option value="any">Any</option>
                    <option value="100000">&pound;100,000+</option>
                    <option value="200000">&pound;200,000+</option>
                    <option value="300000">&pound;300,000+</option>
                    <option value="400000">&pound;400,000+</option>
                    <option value="500000">&pound;500,000+</option>
                </select>
          </div>
            
            <div class="box medium border_light">
            	<select class="medium" name="max">
                	<option value="any">Any</option>
                    <option value="100000">&pound;400+</option>
                    <option value="200000">&pound;600+</option>
                    <option value="300000">&pound;800+</option>
                    <option value="400000">&pound;1000+</option>
            </select>
          </div>
		</div>
        
       <div class="row">
        	<label>Renting or Buying</label>
        </div>
        
        <div class="row">
            <div class="box medium2 border_light">
            	<select class="medium2" name="date">
                	<option value="any">Any, I don't mind</option>
                    <option value="rent">I'm looking to rent</option>
                    <option value="buy">I'm looking to buy</option>
                </select>
            </div>
            
            <div class="left">
          	  <input id="submit" type='image' src='/assets/images/search_btn.jpg' onmouseover="this.src='/assets/images/search_btn_hover.jpg'" onmouseout="this.src='/assets/images/search_btn.jpg'"/>
            </div>
		</div>
        <div class="clear"></div>
        </form>
        
        <h3>Search by Category</h3>
        
        <h4 class="background_medium colour_darkest">Property Type:</h4>
        <ul>
        	<li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Houses <span class="black">(600)</span></a>
            	<ul>
                    <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Detached Houses <span class="black">(200)</span></a></li>
                    <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Semi-detached Houses <span class="black">(300)</span></a></li>
                    <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Terraced Houses <span class="black">(100)</span></a>
                    </li>
                </ul>
            </li>
            
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Flats / Apartments <span class="black">(52)</span></a></li>
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Bungalows <span class="black">(6)</span></a></li>
        </ul>
        
        <h4 class="background_medium colour_darkest">Furnishing:</h4>
        <ul>
        	<li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Furnished <span class="black">(1548)</span></a></li>
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Part Furnished <span class="black">(250)</span></a></li>
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Unfurnished <span class="black">(254)</span></a></li>
        </ul>
        
        <h4 class="background_medium colour_darkest">Type:</h4>
        <ul>
        	<li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Buying <span class="black">(1548)</span></a></li>
        	<li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Long Term Let <span class="black">(1548)</span></a></li>
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Short Term Let <span class="black">(250)</span></a></li>
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">House / Flat Share <span class="black">(254)</span></a></li>
        </ul>
        
        <h4 class="background_medium colour_darkest">Outside Space:</h4>
        <ul>
        	<li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Garden <span class="black">(1548)</span></a></li>
            <li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Parking <span class="black">(250)</span></a></li>
        </ul>
        
        <h4 class="background_medium colour_darkest">Retirement Properties:</h4>
        <ul>
        	<li class="background_light colour_dark"><a class="border_bottom_lightest" href="#">Non-Retirement <span class="black">(1548)</span></a></li>
        </ul>
        <div class="clear">&amp;</div><!--sidebar end-->
        </div><!--sidebar-->
        
        <div id="right_side">
        
        	<div id="search_query" class="border_light background_lightest">
    
            <p>You're Viewing: <span class="black">30 Deanery Close, Sudbury, Suffolk, CO10 1GE</span></p>
            <h2 class="colour_dark">&pound;750/month</h2>
            
            </div><!--search_query-->
            
            
            <div class="result">
               
               <div id="multiple_images">
               
               <h1>Photos</h1>
               
               <div class="image">
               		<a title="Living Room" class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="/assets/images/random_listing4.jpg"><img src="/assets/images/94x94.jpg" alt="image" />
                    </a>
               </div>
               
               <div class="image">
               		<a title="Living Room" class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="/assets/images/random_listing4 - Copy.jpg"><img src="/assets/images/94x94.jpg" alt="image" />
                    </a>
               </div>
               
               <div class="image">
               		<a title="Living Room" class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="/assets/images/random_listing4 - Copy (2).jpg"><img src="/assets/images/94x94.jpg" alt="image" />
                    </a>
               </div>
               
               <div class="image">
               		<a title="Living Room" class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="/assets/images/random_listing4 - Copy (3).jpg"><img src="/assets/images/94x94.jpg" alt="image" />
                    </a>
               </div>
               
               <div class="image">
               		<a title="Living Room" class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="/assets/images/random_listing4 - Copy (4).jpg"><img src="/assets/images/94x94.jpg" alt="image" />
                    </a>
               </div>
               
               <div class="image">
               		<a title="Living Room" class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="/assets/images/random_listing4 - Copy (5).jpg"><img src="/assets/images/94x94.jpg" alt="image" />
                    </a>
               </div>
               
               <div class="image">
               		<a title="Living Room" class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="/assets/images/random_listing4 - Copy (6).jpg"><img src="/assets/images/94x94.jpg" alt="image" />
                    </a>
               </div>
               
               <div class="image">
               		<a title="Living Room" class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="/assets/images/random_listing4 - Copy (7).jpg"><img src="/assets/images/94x94.jpg" alt="image" />
                    </a>
               </div>
               
               <div class="image">
               		<a title="Living Room" class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="/assets/images/random_listing4 - Copy (8).jpg"><img src="/assets/images/94x94.jpg" alt="image" />
                    </a>
               </div>
               
               <div class="image">
               		<a title="Living Room" class="background_light border_medium" onmouseover="this.className='background_lightest border_light'" onmouseout="this.className='background_light border_medium'" href="/assets/images/random_listing4 - Copy (9).jpg"><img src="/assets/images/94x94.jpg" alt="image" />
                    </a>
               </div>
               
               <p>Click one of the photos to see a larger version.</p>
               
               </div><!--multiple image-->
               
               <div id="description">
               
               		<h1>Full Description</h1>
                    
                    <p>Beautiful Executive 3 storey, 6 bedroom househouse in elite area, comprising of fully fitted kitchen/diner &amp; appliances, seperate utility, large lounge, 6 ensuites, family bathroom, Underfloor heating throughout property, 3 car garage with store room, extensive driveway, beautiful back garden with stunning views.</p>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                    
                    <h1>Property Information</h1>
                        <ul>
                        
                            <li>Furnishing: <strong>Unfurnished</strong></li>
                            <li>Date Available: <strong>10/07/2012</strong></li>
                        
                        </ul>
                      
                    
                    <h1>Request details / Contact</h1>
                    
                    <p>Please call <span class="black">01787 123456</span> and quote <span class="black">REF-123456</span> for more details.</p>
                    
                    <h1>Disclaimer:</h1>
                    <p class="grey">Property reference 346_7377174522. The information displayed about this property comprises a property advertisement. yoursite.co.uk makes no warranty as to the accuracy or completeness of the advertisement or any linked or associated information, and yoursite has no control over the content. This property advertisement does not constitute property particulars. The information is provided and maintained by anothercomapny.
                    </p>
               </div>
               
            <div class="clear">&amp;</div><!--result end-->
        	</div><!--result-->
            
        </div><!--right side-->
        
        <div class="clear">&amp;</div><!--sidebar image end-->
       </div><!--sidebar_image-->
       
    </div><!--holder-->
    
    <div class="clear"></div> <!-- holder finished -->
    
    <div class="spacer">&nbsp;</div>
    
    <div id="footer" class="grid_12">
    
    <p class="left">&copy; 2008-2009 The Ultimate Real Estate Theme</p>
    <p class="right"><a href="#">Terms &amp; Conditions</a> | <a href="#">Contact</a></p>
    
    </div>
    
</div><!-- container_12 -->
<div class="simple_overlay background_lightest border_light" id="gallery"> 
 					<div class="close">&nbsp;</div>
                    <!-- "previous image" action --> 
                    <a class="prev">prev</a> 
                 
                    <!-- "next image" action --> 
                    <a class="next">next</a> 
                 
                    <!-- load indicator (animated gif) --> 
                    <img class="progress" src="http://static.flowplayer.org/tools/img/overlay/loading.gif" alt="loading..." /> 
                    
</div>

<script type="text/javascript">
$("#multiple_images a").overlay({ 
 
			// each trigger uses the same overlay with the id "gallery" 
			target: '#gallery', 
		 
			// optional exposing effect 
			expose: '#f1f1f1' 
		 
		// let the gallery plugin do its magic! 
		}).gallery({ 
		 
			// the plugin accepts its own set of configuration options 
			speed: 800 
		});
</script>
</body>

</html>
