<div class="container_12">



	<div class="clear"></div>
	<!-- Header finished -->

	<div class="spacer">&nbsp;</div>


	<div id="holder" class="grid_12 border_light">
		<div id="sidebar_image">

			<div id="sidebar">
				<h4 class="background_medium colour_darkest"></h4>
				<ul>
					<li />
				</ul>

				<div class="clear">&amp;</div>
				<!--sidebar end-->
			</div>
			<!--sidebar-->

			<div id="right_side">

				<div id="search_query" class="border_light background_lightest">

					<p>
						You're Viewing: <span class="black">30 Deanery Close, Sudbury,
							Suffolk, CO10 1GE</span>
					</p>
					<h2 class="colour_dark">&pound;750/month</h2>

				</div>
				<!--search_query-->


				<div class="result">

					<div id="multiple_images">

						<h1>Photos</h1>

						<div class="image">
							<a title="Living Room" class="background_light border_medium"
								onmouseover="this.className='background_lightest border_light'"
								onmouseout="this.className='background_light border_medium'"
								href="/assets/images/random_listing4.jpg"><img
								src="/assets/images/94x94.jpg" alt="image" /> </a>
						</div>

						<div class="image">
							<a title="Living Room" class="background_light border_medium"
								onmouseover="this.className='background_lightest border_light'"
								onmouseout="this.className='background_light border_medium'"
								href="/assets/images/random_listing4 - Copy.jpg"><img
								src="/assets/images/94x94.jpg" alt="image" /> </a>
						</div>

						<div class="image">
							<a title="Living Room" class="background_light border_medium"
								onmouseover="this.className='background_lightest border_light'"
								onmouseout="this.className='background_light border_medium'"
								href="/assets/images/random_listing4 - Copy (2).jpg"><img
								src="/assets/images/94x94.jpg" alt="image" /> </a>
						</div>

						<div class="image">
							<a title="Living Room" class="background_light border_medium"
								onmouseover="this.className='background_lightest border_light'"
								onmouseout="this.className='background_light border_medium'"
								href="/assets/images/random_listing4 - Copy (3).jpg"><img
								src="/assets/images/94x94.jpg" alt="image" /> </a>
						</div>

						<div class="image">
							<a title="Living Room" class="background_light border_medium"
								onmouseover="this.className='background_lightest border_light'"
								onmouseout="this.className='background_light border_medium'"
								href="/assets/images/random_listing4 - Copy (4).jpg"><img
								src="/assets/images/94x94.jpg" alt="image" /> </a>
						</div>

						<div class="image">
							<a title="Living Room" class="background_light border_medium"
								onmouseover="this.className='background_lightest border_light'"
								onmouseout="this.className='background_light border_medium'"
								href="/assets/images/random_listing4 - Copy (5).jpg"><img
								src="/assets/images/94x94.jpg" alt="image" /> </a>
						</div>

						<div class="image">
							<a title="Living Room" class="background_light border_medium"
								onmouseover="this.className='background_lightest border_light'"
								onmouseout="this.className='background_light border_medium'"
								href="/assets/images/random_listing4 - Copy (6).jpg"><img
								src="/assets/images/94x94.jpg" alt="image" /> </a>
						</div>

						<div class="image">
							<a title="Living Room" class="background_light border_medium"
								onmouseover="this.className='background_lightest border_light'"
								onmouseout="this.className='background_light border_medium'"
								href="/assets/images/random_listing4 - Copy (7).jpg"><img
								src="/assets/images/94x94.jpg" alt="image" /> </a>
						</div>

						<div class="image">
							<a title="Living Room" class="background_light border_medium"
								onmouseover="this.className='background_lightest border_light'"
								onmouseout="this.className='background_light border_medium'"
								href="/assets/images/random_listing4 - Copy (8).jpg"><img
								src="/assets/images/94x94.jpg" alt="image" /> </a>
						</div>

						<div class="image">
							<a title="Living Room" class="background_light border_medium"
								onmouseover="this.className='background_lightest border_light'"
								onmouseout="this.className='background_light border_medium'"
								href="/assets/images/random_listing4 - Copy (9).jpg"><img
								src="/assets/images/94x94.jpg" alt="image" /> </a>
						</div>

						<p>Click one of the photos to see a larger version.</p>

					</div>
					<!--multiple image-->

					<div id="description">

						<h1>Full Description</h1>

						<p>Beautiful Executive 3 storey, 6 bedroom househouse in elite
							area, comprising of fully fitted kitchen/diner &amp; appliances,
							seperate utility, large lounge, 6 ensuites, family bathroom,
							Underfloor heating throughout property, 3 car garage with store
							room, extensive driveway, beautiful back garden with stunning
							views.</p>
						<p>Lorem Ipsum is simply dummy text of the printing and
							typesetting industry. Lorem Ipsum has been the industry's
							standard dummy text ever since the 1500s, when an unknown printer
							took a galley of type and scrambled it to make a type specimen
							book. It has survived not only five centuries, but also the leap
							into electronic typesetting, remaining essentially unchanged. It
							was popularised in the 1960s with the release of Letraset sheets
							containing Lorem Ipsum passages, and more recently with desktop
							publishing software like Aldus PageMaker including versions of
							Lorem Ipsum.</p>

						<h1>Property Information</h1>
						<ul>

							<li>Furnishing: <strong>Unfurnished</strong></li>
							<li>Date Available: <strong>10/07/2012</strong></li>

						</ul>


						<h1>Request details / Contact</h1>

						<p>
							Please call <span class="black">01787 123456</span> and quote <span
								class="black">REF-123456</span> for more details.
						</p>

						<h1>Disclaimer:</h1>
						<p class="grey">Property reference 346_7377174522. The information
							displayed about this property comprises a property advertisement.
							yoursite.co.uk makes no warranty as to the accuracy or
							completeness of the advertisement or any linked or associated
							information, and yoursite has no control over the content. This
							property advertisement does not constitute property particulars.
							The information is provided and maintained by anothercomapny.</p>
					</div>

					<div class="clear">&amp;</div>
					<!--result end-->
				</div>
				<!--result-->

			</div>
			<!--right side-->

			<div class="clear">&amp;</div>
			<!--sidebar image end-->
		</div>
		<!--sidebar_image-->

	</div>
	<!--holder-->

	<div class="clear"></div>
	<!-- holder finished -->

	<div class="spacer">&nbsp;</div>

	

</div>
<!-- container_12 -->
<div
	class="simple_overlay background_lightest border_light" id="gallery">
	<div class="close">&nbsp;</div>
	<!-- "previous image" action -->
	<a class="prev">prev</a>

	<!-- "next image" action -->
	<a class="next">next</a>

	<!-- load indicator (animated gif) -->
	<img class="progress"
		src="http://static.flowplayer.org/tools/img/overlay/loading.gif"
		alt="loading..." />

</div>

<script type="text/javascript">
$("#multiple_images a").overlay({ 
 
			// each trigger uses the same overlay with the id "gallery" 
			target: '#gallery', 
		 
			// optional exposing effect 
			expose: '#f1f1f1' 
		 
		// let the gallery plugin do its magic! 
		}).gallery({ 
		 
			// the plugin accepts its own set of configuration options 
			speed: 800 
		});
</script>
