<?php /**this file will contain menu used withUser controller**/?>   
<div class='link'><?php echo '<a href=\''.$this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'edit', 'id' => 0 ) ).'\'>AddUser</a>';?></div>
<div class='link'><?php echo '<a href=\''.$this->url(array('module' => $this->mdl,'controller' => 'user','action' => 'view','id' => $this->user->id )).'\'>ViewUser</a>'; ?></div>
<div class='link'><?php echo '<a href=\''.$this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'upload', 'id' => $this->user->id)).'\'>Add Image</a>';?></div>
<div class='link'><?php echo '<a href=\''.$this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'attributes', 'id' => $this->user->id)).'\'>Attributes</a>';?></div>
<div class='link'><?php echo '<a href=\''.$this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'detail', 'id' => $this->user->id)).'\'>Add Details</a>';?></div>
<div class='link'><?php echo '<a href=\''.$this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'video', 'id' => $this->user->id)).'\'>Add Video</a>';?></div>
<div class='link'><?php echo '<a href=\''.$this->url(array('module' => 'admin', 'controller' => 'user', 'action' => 'index', 'id' => 0 )).'\'>Back</a>';?></div>