<ul class="menu">
    <li><a class="link" href="/admin/coupon/index"><span class="add-link">Deals & Coupons</span></a></li>
    <li><a class="link" href="/admin/coupon/edit"><span class="add-link">Edit Coupon</span></a></li>
    <li><a class="link" href="/admin/coupon/company"><span class="add-link">Company</span></a></li>
    <li><a class="link" href="/admin/coupon/companies"><span class="add-link">Companies</span></a></li>
    <li><a class="link" href="/admin/coupon/group"><span class="add-link">Group</span></a></li>
    <li><a class="link" href="/admin/coupon/groups"><span class="add-link">Groups</span></a></li>
    <li><a class="link" href="/admin/coupon/item"><span class="add-link"> Edit Product </span></a></li>
    <li><a class="link" href="/admin/coupon/items"><span class="add-link">Products </span></a></li>
</ul>