<div class="span-24 last">
    <div id="" class='wrapper-content-left-column span-5'>
            <?php echo $this->render('coupon/_menu.phtml');?>
    </div>
   <div class="wrapper-content-right-column cms-form-div span-19 last" id="">
            <?php echo $this->message( $this->message ); ?>

            <?php foreach( $this->items as $k => $company ): $company = (object)$company; ?>
                <div class="padded-8 span-19 last" >
                    <h4><?php echo $company->name;?></h4>
                    <span class="description"><?php echo $company->description;?></span>
                     <div class="edit-widget">
                        <?php echo $this->edit( array( "edit" => "/admin/coupon/company/".$company->id ), array( "span" => true ) );?>
                    </div>
                </div>
                <?php endforeach;?>
    </div>
</div>