<div class="span-24 last">
<div id="" class='wrapper-content-left-column span-5'>
            <?php echo $this->render('coupon/_menu.phtml');?>
    </div>
   <div class="wrapper-content-right-column cms-form-div span-19 last" id="">
            <?php echo $this->message( $this->message ); ?>
            <?php foreach( $this->items as $k => $item ): $item = (object)$item; ?>
               <div class="padded-8 span-19 last" >
                    <h4><?php echo $item->name;?></h4>
                    <span class="description"><?php echo $item->description;?></span>
                    <span class="tags"><?php echo $item->tags;?></span>
                    <div class="edit-widget">
                        <?php echo $this->edit( array( "edit" => "/admin/coupon/edit/".$item->id ), array( "span" => true ) );?>
                    </div>
               </div>                
            <?php endforeach;?>
    </div>
</div>