<div id="" class="" style="margin: auto 0;">
	<form action='' method='post'> 
    	<?php if($this->message ):?>
			<?php echo $this->message($this->message );?>
    	<?php endif;?>

        <?php
            echo "Deleting the account";
        ?>

        <input type='hidden' name='pid' value='<?php $this->id;?>' />
    	<input type='submit' id='button'  class='button' value='Delete'/>
    </form>
</div>