<?php
/**
 * This file has been designed to reduce repetitive menu codes inside tax view files
 */	
?>
<!--  this link is not in the right place-->
<div class='add-link link'><?php echo '<a href=\''.$this->url(array('module' => $this->mdl, 'controller' => 'tax', 'action' => 'index', 'id' => '')).'\'>Index</a>';?></div>
<div class='add-link link'><?php echo '<a href=\''.$this->url(array('module' => $this->mdl, 'controller' => 'tax', 'action' => 'rate', 'id' => '')).'\'>Tax Rate</a>';?></div>	
<div class='add-link link'><?php echo '<a href=\''.$this->url(array('module' => $this->mdl, 'controller' => 'tax', 'action' => 'classes', 'id' => '')).'\'>Tax Classes</a>';?></div>	
<div class='add-link link'><?php echo '<a href=\''.$this->url(array('module' => $this->mdl, 'controller' => 'tax', 'action' => 'tclass', 'id' => '')).'\'>New Tax Classes</a>';?></div>	
<div class='add-link link'><?php echo '<a href=\''.$this->url(array('module' => $this->mdl, 'controller' => 'tax', 'action' => 'zones', 'id' => '')).'\'>Tax Zones</a>';?></div>
<div class='add-link link'><?php echo '<a href=\''.$this->url(array('module' => $this->mdl, 'controller' => 'tax', 'action' => 'zone', 'id' => '')).'\'>New Tax Zone</a>';?></div>
<div class='add-link link'><?php echo '<a href=\''.$this->url(array('module' => $this->mdl, 'controller' => 'tax', 'action' => 'country', 'id' => '')).'\'>New Country</a>';?></div>	
<div class='add-link link'><?php echo '<a href=\''.$this->url(array('module' => $this->mdl, 'controller' => 'tax', 'action' => 'countries', 'id' => '')).'\'>Countries</a>';?></div>