<div class="span-24 last">
<?php echo $this->title($this->title); ?>
<div id="" class='wrapper-content-left-column span-4'><?php echo $this->render('tax/_menu.phtml');?></div>
<div class='wrapper-content-left-column store-form-div span-19 last'>
    <form action='' method='post'>
    <?php echo $this->message($this->message );?>
    	<?php
        if($this->content){
            echo $this->content;
        ?>
    	<br/>
    	<input type='hidden' name='pid' value='<?php echo $this->id;?>' />
    	<input type='submit' id='button'  class='button' value='<?php echo $this->option_contry == 0? 'Disable' : 'Enable'?>'/>
        <?php
            }
        ?>
    </form>
</div>
</div>