<div id="" class="">
 <?php echo $this->title($this->title); ?>
 <?php echo $this->message( $this->message );	?>
   <div class='back-div-section span-3'>
   <a href = "<?php
		echo $this->url(
			array('module' => $this->mdl,
				  'controller' => 'store',
				  'action' => 'index'));?>">Back</a>
   </div>
    <div class="store-form-div span-20" id="">
   	<?php echo "<div class='widget'><div class='head'><h5 class=''>...</h5></div>".( $this->form)."</div>";?>
        <br>
   </div>

</div>