<div class="span-24 last">
<?php echo $this->title($this->title); ?>
<div id="" class='wrapper-content-left-column span-4'>		
	<?php echo $this->render('tax/_menu.phtml');?>	
</div>
<div class='wrapper-content-left-column store-form-div span-19 last'>	
 <?php echo $this->message( $this->message );?>
 <?php echo "<div class='widget'><div class='head'><h5 class=''>...</h5></div>".( $this->form)."</div>";?>   
</div>
</div>