<div class='link'><?php echo '<a href=\'/admin/task/edit\'>Add task</a>';?></div>
<div class='link'><?php echo '<a href=\'/admin/task/view\'>View task</a>'; ?></div>
<div class='link'><?php echo '<a href=\'/admin/task/upload\'>Add Image</a>';?></div>
<div class='link'><?php echo '<a href=\'/admin/task/details\'>Details</a>';?></div>
<div class='link'><?php echo '<a href=\'/admin/task/detail\'>Add Details</a>';?></div>
<div class='link'><?php echo '<a href=\'/admin/task/video\'>Add Video</a>';?></div>
<div class='link'><?php echo '<a href=\'/admin/task/index\'>Back</a>';?></div>