<div id="" class="">
<?php echo $this->title($this->title); ?>
<?php echo $this->message( $this->message );	?>
   <div class="wrapper-content-left-column span-4">
      <?php echo $this->render('task/_menu.phtml');?>
   </div>
   <div class="wrapper-content-right-column span-19 last">   
   		<?php echo "<div class='widget'><div class='head'><h5 class=''>...</h5></div>".( $this->form)."</div>";?>
   </div>
   <div class='h-separator'></div>
</div>