<?php echo $this->title($this->title); ?>
<?php echo $this->message( $this->message );	?>
<div id='' class='span-24 last' >    
    <div class="wrapper-content-left-column span-4">
      <?php echo $this->render('task/_menu.phtml');?>
    </div>
    
<div class="wrapper-content-right-column span-20 last">
<div  class='table-div' id='admin-product-index-table span-24 last'>
	<!-- the header of the table  -->
	<div class='table-header-div' ></div>
	<?php if( is_array($this->data) ):
    foreach($this->data as $k => $entry): ?>
  	<?php if( !isset($odd) ) $odd = 0; ?>   	
  	<div class='table-row-div <?php echo ( (++$odd & 1)? 'odd':'even')?>'>
          <div  class='table-cell-div nano-cell' >
          <?php echo '<a href=\''.$this->url(array('action'=>'view','id'=>$entry['id'])).'\'>'.$entry['id'].'</a>';?></div>
  		    <div  class='table-cell-div medium-cell'><?php echo '<a href=\''.$this->url(array('action'=>'view','id'=>$entry['id'])).'\'>'.$entry['name'].'</a>'; ?></div>
          <div  class='table-cell-div'>cell</div>       
          <div  class='table-cell-div'>cell</div>
          <div  class='table-cell-div'>cell</div>
          <div  class='table-cell-div small-cell' ><?php echo $entry['created']; ?></div>
          <div  class='table-cell-div medium-cell' >
  			<?php echo '<a href=\''.$this->url(array('action'=>'edit','id'=>$entry['id'])).'\'>Edit</a>';?>
  			<?php echo '<a href=\''.$this->url(array('action'=>'delete','id'=>$entry['id'])).'\'>Delete</a>';?>
  			<?php echo '<a href=\''.$this->url(array('action'=>'attributes','id'=>$entry['id'])).'\'>Attributes</a>';?>
  		</div>
    </div>
	<?php endforeach;	
	      endif;?>
	<!--  the footer of the table + paging division -->
	<div class='table-footer-div' >
		<div  class='table-paging-div' >
				<?php 
					$links = '';
					if ( $this->show_paged_links )
						$links = implode ( $this->paged_links, " | ");	
					echo ( $links )?' Pages '.$links : ''; 	
				?>	
			</div>
	</div>
<!-- end of the table  -->
</div>
</div>
</div>