<div id='' class='span-24 last'>    
<div class="wrapper-content-left-column span-4"><?php echo $this->render('task/_menu.phtml');?></div>    
<div class="wrapper-content-right-column span-20 last">
	<!--there is a need to add the property being treated-->	
	<!-- the header of the table  -->
	<?php $_class = ( $this->error ) ? "error" : "info"; ?>
	<?php echo $this->message( $this->message, array( 'class' => $_class ) ); ?>
	<?php echo "<div class='widget'><div class='head'><h5 class=''>...</h5></div>".( $this->form)."</div>";?>
	<?php if( is_array($this->data) ): ?>
    <?php foreach($this->data as $k => $_o ): ?>
  	<?php if( !isset($odd) ) $odd = 0; ?>   	
  		<?php echo $this->task( $_o, array( 'class' => "span-18 last ".( (++$odd & 1)? 'odd':'even')." " ) ); ?>
	<?php endforeach; ?>	
	<?php endif;?>
	<div  class='table-paging-div' >
		<?php 
			$links = '';
			if ( $this->show_paged_links )
				$links = implode ( $this->paged_links, " | ");	
			echo ( $links )?' Pages '.$links : ''; 	
		?>	
	</div>
</div>
</div>
</div>