<div id="" class="">
	<?php echo $this->title($this->title); ?>
    
    
    <div class="wrapper-content-left-column span-4">
    	<?php echo $this->smenu;?> 
    </div>
    
    
    
   <div class="wrapper-content-right-column span-19 last">	
   <?php if ($this->items ): ?> 
   <div id='admin-media-banners-table' class='table-div' >
   <div class='table-header-div' >
    		<div  class='table-cell-div small-cell' >Title</div>
    		<div  class='table-cell-div small-cell' >Caption</div>
    		<div  class='table-cell-div small-cell' >Media</div>
    		<div  class='table-cell-div small-cell' >Order</div>
    		<div  class='table-cell-div small-cell' >Displayed</div>
    		<div  class='table-cell-div small-cell' >Action</div>
    	</div>
    	<?php foreach ( $this->items as $k => $datum ):
    		
    		$type = preg_split ('/_/' , $datum['media_key']);
    		if ( ( $type[1] == 'html' || $type[1]  == 'flash' || $type[1]  == 'image' ) && ($datum['media_value'] != '' ) ) 
    			 $type = $type[1];
    		else $type = 'No File';    		
    	?>	
    		<div class='table-row-div'>
    						<div class='table-cell-div small-cell' ><?php echo '<a href=\''.$this->url( array( 'action' => 'banner' ,  'id' => $datum['id'] ) ).'\' >'.$datum['title'].'</a>'; ?></div>
    						<div class='table-cell-div small-cell' ><?php echo $datum['caption']; ?></div>
    						<div class='table-cell-div small-cell' ><?php echo $type; ?></div>
    						<div class='table-cell-div small-cell' ><?php echo $this->ajax_input_helper->ajaxInput( array ( 'type' => 'text', 'value' => $datum['media_order'],  'class' => 'input-banner',   'id' => 'banner_order_input-'.$datum['id'], 'style' => 'width:70px; margin: 0px; height: 14px;') ); ?></div>
    						<div class='table-cell-div small-cell' ><?php echo $this->ajaxCheckable( array ( 'status' => ( $datum['displayed'] == 1),    'name' => 'banner', 'class' => 'checkbox-banner',   'id' => 'banner-'.$datum['id'] ) ); ?></div>
    						<div class='table-cell-div small-cell' >
    							<?php echo '<a href=\''.$this->url(array('action'=>'banner','id'=>$datum['id'])).'\'>Edit</a>';?>
								<?php echo '<a href=\''.$this->url(array('action'=>'delete','id'=>$datum['id'])).'\'>Delete</a>';?>
							</div>	
    					 </div>
    	
    		<?php endforeach; ?> 
    	</div>
     <?php endif; ?> 
     </div>
    
</div>