<div id="" class="" style="margin: auto 0;">
<?php echo $this->title($this->title); ?>
<form action='' method='post'> 
    	<?php if($this->message ):?>
			<?php echo $this->message($this->message );?>
    	<?php else: ?>
    		<?php echo $this->content;?>
    		<input type='hidden' name='pid' value='<?php $this->id;?>' />
    		Delete also files on the disk <input type='checkbox' id='checkbox'   name='andFiles'  class='checkbox' checked = 'checked' />
    		<br/>
    		<input type='submit' id='button'  class='button' value='Delete'/>
    	<?php endif;?>
    	<?php echo $this->link_to_media; ?>
    </form>
  </div> 
