<div id="" class="">
<?php echo $this->title($this->title); ?>


<div class="wrapper-content-left-column span-4">
	<?php  $banner = $this->smenu; echo $banner;  ?>
</div>

<div class="wrapper-content-right-column span-19 last">
    <div class="cms-form-div" id="admin-banner-upload-div">
	<?php if( $this->message ) echo $this->message( $this->message );	?>
	<?php if( $this->notification  ) echo $this->notification;?>	
	<small>
		the width of the banner file, has to be of the same size, as the width you want to be displayed on the front end.<br/> 
		there is no image crop activated for this version.
	</small>
	<?php echo "<div class='widget'><div class='head'><h5 class=''>...</h5></div>".( $this->form)."</div>";?>   
   </div>   
 <div class='h-separator'>
 	<?php echo $this->image; ?>
	<?php  echo $this->upload_link;?>
 </div>
 </div>
</div>
<script>
$(document).ready(function (){
document.getElementById('description-label').style.clear = 'both';
});
</script>