<?php
  
 
echo "<div class='menu-item'><a href='".
			$this->url(array('controller' => $this->menu_item->controller,
				'action' => $this->menu_item->action, 'id' => ''  
			))."'>".(isset($this->menu_item->title)?$this->menu_item->title:$this->menu_item->action)."</a>";
		echo "</div>";	
/*  
echo '<div class=\'menu-item\'><a href=\'./'.$this->menu_item->controller.'/'.$this->menu_item->action.'\'>'.(isset($this->menu_item->title)?$this->menu_item->title:$this->menu_item->action).'</a>';
echo '</div>';	
 */
?>