
<div id='' class='span-24 last' >    
    <div class="wrapper-content-left-column span-4">
      <?php echo $this->render('property/_menu.phtml');?>
    </div>    
<div class="wrapper-content-right-column span-20 last">
<form accept-charset="utf-8">
   <?php $this->data = (object)$this->data;?>
    <?php
        if( is_array( $this->data->media ) ){
            $_media = is_array( $this->data->media[0] ) ? $this->data->media[0] : $this->data->media;
            $_media = ( object ) $_media;
        }
        $_im = is_object ( $_media ) ? '/assets/img/t/'.$_media->media_value : '/assets/img/gallery.png';
        echo $this->property( $this->data->property , array( 'long' => true, 'image' => $_im ));
    ?>




       <?php 
	   		echo $this->message;  
			$odd = 0; 
		?>
       <?php foreach($this->booking as $k => $_o ): ?>
        <?php
            
			$alt = ( (++$odd)&1 )? "even" : "odd";
            $_o = is_array($_o) ? (object)$_o : $_o;
            $_edit = $this->edit( array( 'Details' => "/admin/booking/edit/".$_o->booking->id."/?property=".$this->property->id."&user=".$_o->user->id, 'Reject' => "/admin/booking/reject/".$_o->booking->id."" ) );
        ?>
	<?php echo $this->booking( $_o->booking , array( 'class' => 'span-18 last '.$alt, 'user' => $_o->user , 'image' => "" , 'property' => $this->property , 'details' => $_o->details, 'editing' => $_edit  ) ); ?>
        <?php endforeach;?>
    <!--  the footer of the table + paging division -->
    <div  class='table-paging-div' >
        <?php   $links = '';
             if ( $this->show_paged_links )$links = implode ( $this->paged_links, " | "); echo ( $links )?' Pages '.$links : '';
        ?>
    </div>
</form>
</div>
</div>