<div id="" class="" style="margin: auto 0;">
		<?php echo $this->title($this->title); ?>

	<form action='' method='post'> 
    	<?php if($this->message ):?>
			<?php echo $this->message($this->message );?>
    	<?php endif;?>
		<?php echo $this->content;?>
    	<br/>
    	<input type='hidden' name='pid' value='<?php $this->id;?>' />
    	<input type='submit' id='button'  class='button' value='Delete'/>
    	<?php echo $this->link_to_products; ?>
    </form>
</div>