<?php echo $this->message( $this->message , array( 'class' => $this->_class ) );?>
<div id='' class='span-24 last' >    
<div class="wrapper-content-left-column span-4"><?php echo $this->render('property/_menu.phtml');?></div>    
<div class="wrapper-content-right-column span-20 last">

    <?php $this->data = (object)$this->data;?>
    <?php
        if( is_array( $this->data->media ) ){
            $_media = is_array( $this->data->media[0] ) ? $this->data->media[0] : $this->data->media;
            $_media = ( object ) $_media;
        }
        $_im = is_object ( $_media ) ? '/assets/img/t/'.$_media->media_value : '/assets/img/gallery.png';
        echo $this->property( $this->data->property , array( 'long' => true, 'image' => $_im ));
    ?>




    <?php if( !isset($odd) ) { $odd = 0; } ?>
    <?php if( is_array($this->data->locations) ): ?>
        <?php foreach( $this->data->locations as $k => $_o ): ?>
                <?php $_o = (object)$_o;?>
		<?php
                    $_options = array();
                    $_options['class'] = 'ajax-checkable';
                    $_options['value'] = $this->property->id;
                    $_options['id'] = $_o->id;
                    $_options['data'] = "{url:/admin/property/jxlandlord/?ajx=true, property: ".$this->property->id."}";
                    $_options['class'] = 'ajax-checkable';
                    $_options['status'] =  false;
                ?>
                <?php $_checkbox = $this->ajaxCheckable( $_options );?>
                <?php echo $this->location( $_o,  array( 'class' => ' span-18 last '.( (++$odd & 1) ? 'odd':'even').'',  'checkbox' => $_checkbox ) ); ?>
  	<?php endforeach;?>
    <?php endif;?>
    <div  class='table-paging-div'>
        <?php   $links = '';
                if ( $this->show_paged_links )
                        $links = implode ( $this->paged_links, " | ");
                echo ( $links )?' Pages '.$links : '';
        ?>
    </div>
</div>
</div>
