<div id="" class="">
<?php echo $this->title($this->title); ?>
   <div class="wrapper-content-left-column span-4">
   	<?php  echo $this->render('property/_menu.phtml'); ?>
   </div> 
   <div class="wrapper-content-left-column  span-19 last">
	<?php echo $this->message( $this->message );	?>
    <?php echo "<div class='widget'><div class='head'><h5 class=''>...</h5></div>".( $this->form)."</div>"; ?>
   </div>
</div>