<?php echo $this->title($this->title); ?>
<?php echo $this->message( $this->message , array( 'class' => $this->_class ) );?>
<div id='' class='span-24 last' >    
    <div class="wrapper-content-left-column span-4">
      <?php echo $this->render('property/_menu.phtml');?>
    </div>    
<div class="wrapper-content-right-column span-20 last">
<form accept-charset="utf-8">
<div  class='table-div'>
    <!-- the header of the table  -->
    <?php if( is_array($this->data) ): ?>
        <?php foreach($this->data as $k => $_o ): ?>
            <?php echo $this->photo( $_o ) ?>
        <?php endforeach;?>
    <?php endif;?>
    <!--  the footer of the table + paging division -->
    <div class='table-footer-div' >
    <div  class='table-paging-div' >
        <?php   $links = '';
                if ( $this->show_paged_links )
                        $links = implode ( $this->paged_links, " | ");
                echo ( $links )?' Pages '.$links : '';
        ?>
    </div>
    </div>
<!-- end of the table  -->
</div>
</form>
</div>
</div>