<div class='span-24 last'>
<div class="wrapper-content-left-column span-4">
  <?php echo $this->render('property/_menu.phtml');?>
</div>
<div class="wrapper-content-right-column span-20 last">
    <?php $this->data = (object)$this->data;?>
    <?php
        if( is_array( $this->data->media ) ){
            $_media = (isset($this->data->media[0]) && is_array( $this->data->media[0] )) ? $this->data->media[0] : $this->data->media;
            $_media = ( object ) $_media;
        }
        $_im = ( is_object ( $_media ) && isset($_media->media_value)) ? '/assets/img/t/'.$_media->media_value : '/assets/gallery.png';
        echo $this->property( $this->data->property , array( 'long' => true, 'image' => $_im ));
    ?>


    <div class="span-18 last">Details: </div>
    <?php
        $_edit = ""; $odd = 0;
        foreach( $this->data->details as $k => $detail ):
           $alt = ( (++$odd)&1 )? "even" : "odd";
            echo $this->feature( $detail, array( 'editing' => $_edit ,'long' => true, 'class' => "span-18 last long $alt"  ) );
        endforeach;
    ?>

    <div class="span-18 last">Media: </div>
    <?php
        echo $this->carousel( $this->data->media, array( 'class' => 'span-18 last', 'width' => 'small') );
    ?>

    <div class="span-18 last">Leases: </div>
    <?php
        $_edit = ""; $odd = 0;
        foreach( $this->data->leases as $k => $lease ):
           $alt = ( (++$odd)&1 )? "even" : "odd";
            echo $this->lease( $detail, array( 'editing' => $_edit ,'long' => true, 'class' => "span-18 last long $alt"  ) );
        endforeach;
    ?>


    <div class="span-18 last">Landlords: </div>
    <?php
        $_edit = ""; $odd = 0;
        foreach( $this->data->landlords as $k => $user ):
           $alt = ( (++$odd)&1 )? "even" : "odd";
            echo $this->landlord( $user, array( 'editing' => $_edit ,'long' => true, 'class' => "span-18 last long $alt"  ) );
        endforeach;
    ?>

    <div class="span-18 last">Booking: </div>
    <?php
        $_edit = ""; $odd = 0;
        foreach( $this->data->booking as $k => $booking ):
           $alt = ( (++$odd)&1 )? "even" : "odd";
            echo $this->booking( $booking, array( 'editing' => $_edit ,'long' => true, 'class' => "span-18 last long $alt"  ) );
        endforeach;
    ?>

    <div class="span-18 last">Tenants: </div>
    <?php
        $_edit = ""; $odd = 0;
        foreach( $this->data->booking as $k => $booking ):
           $alt = ( (++$odd)&1 )? "even" : "odd";
            echo $this->booking( $booking, array( 'editing' => $_edit ,'long' => true, 'class' => "span-18 last long $alt"  ) );
        endforeach;
    ?>

    <div class="span-18 last">Tasks: </div>
    <?php
        $_edit = ""; $odd = 0;
        foreach( $this->data->tasks as $k => $task ):
           $alt = ( (++$odd)&1 )? "even" : "odd";
            echo $this->task( $task, array( 'editing' => $_edit ,'long' => true, 'class' => "span-18 last long $alt"  ) );
        endforeach;
    ?>


</div>
</div> 