<div id="" class="product-upload">
   	<?php echo $this->title($this->title); ?>
	<div class="wrapper-content-left-column span-4">
     <?php  echo $this->render('property/_menu.phtml'); ?>
    </div>   

 <div class="wrapper-content-right-column span-20 last">
   	<!-- has been replaced by a view helper  -->
  	<?php echo $this->message( $this->message );	?>
  	<?php echo $this->success_message ? $this->success_message : ""; ?>
   	<?php 
   		try{
   			echo "<div class='widget'><div class='head'><h5 class=''>...</h5></div>".( $this->form)."</div>";
   		}catch (Exception $e ){
   			echo " <div class = 'error' > ".$e->getMessage()."</div>";
   		}
   ?>
<?php echo $this->media;?>
</div>
</div>