<ul class="menu">
    <li><a class="link" href="/admin/coupon/index"><span class="add-link">Deals & Coupons</span></a></li>
    <li><a class="link" href="/admin/settings/amenity"><span class="add-link">Add Amenity</span></a></li>
    <li><a class="link" href="/admin/settings/amenities"><span class="add-link">Amenities</span></a></li>
    <li><a class="link" href="/admin/settings/plan"><span class="add-link">Add Plan</span></a></li>
    <li><a class="link" href="/admin/settings/plans"><span class="add-link">Plans</span></a></li>
    <li><a class="link" href="/admin/settings/message"><span class="add-link">Notice & Message</span></a></li>
    <li><a class="link" href="/admin/settings/billing"><span class="add-link">Billing</span></a></li>
<!--comming  soon-->
    <li><a class="link" href="/admin/settings/profile"><span class="add-link">Public Profile</span></a></li>
    <li><a class="link" href="/admin/settings/account"><span class="add-link">Account Admin</span></a></li>
    <li><a class="link" href="/admin/settings/deals"><span class="add-link">Deals</span></a></li>
    <li><a class="link" href="/admin/settings/address"><span class="add-link">Address</span></a></li>
    <li><a class="link" href="/admin/settings/message"><span class="add-link">Message</span></a></li>
    <li><a class="link" href="/admin/settings/address"><span class="add-link">Address</span></a></li>
    <li><a class="link" href="/admin/settings/contact"><span class="add-link">Contact</span></a></li>
    <li><a class="link" href="/admin/settings/plan"><span class="add-link">Plan</span></a></li>
    <li><a class="link" href="/admin/settings/message"><span class="add-link">Notice & Message</span></a></li>
    <li><a class="link" href="/admin/settings/leases"><span class="add-link">Leases</span></a></li>
    <li><a class="link" href="/admin/settings/lease"><span class="add-link">Add Lease</span></a></li>
    <!--comming  soon-->
    <li><a class="link" href="/admin/settings/billing"><span class="add-link">Agrement</span></a></li>
    <li><a class="link" href="/admin/settings/billing"><span class="add-link">Lease requirement</span></a></li>
    <!--(questionnaire or survey)-->
</ul>