<div class="span-24 last">
    <div id="" class='wrapper-content-left-column span-5'>
            <?php echo $this->render('settings/_menu.phtml');?>
    </div>
    <div class="wrapper-content-right-column cms-form-div span-19 last" id="">
            <?php echo $this->message( $this->message ); ?>
        <?php echo "<div class='widget'><div class='head'><h5 class=''>...</h5></div>".( $this->form)."</div>";?>
     </div>
</div>