<div class="span-24 last">
    <div id="" class='wrapper-content-left-column span-5'>
            <?php echo $this->render('settings/_menu.phtml');?>
    </div>
    <div class="wrapper-content-right-column cms-form-div span-19 last" id="">
       <?php echo $this->message( $this->message , array( "class" => $this->error ) ); ?>
       <?php
            $odd = 0;
            #looping throught amenities
            foreach( $this->data as $k => $datum ):
                $datum  = ( object )$datum;
                $_edit = $this->edit( array( "edit" => "/admin/settings/lease/".$datum->id, "delete" => "/admin/settings/delete/?object=lease&id=".$datum->id ) );
                $_cls = ( (++$odd & 1) ? 'odd':'even' );
                echo $this->leaseType( $datum , array( "class" => " table span-18 last ".$_cls , "editing" =>$_edit ) );
            endforeach;
        ?>
     </div>
</div>