<div class="span-24 last">
    <div id="" class='wrapper-content-left-column span-5'>
            <?php echo $this->render('settings/_menu.phtml');?>
    </div>
    <div class="wrapper-content-right-column cms-form-div span-19 last" id="">
       <?php echo $this->message( $this->message ); ?>
       <?php
            $odd = 0;
            #looping throught amenities
            foreach( $this->plans as $k => $plan ):
                $plan  = ( object )$plan;
                $_edit = $this->edit( array( "edit" => "/admin/settings/plan/".$plan->id, "delete" => "/admin/settings/delete/?object=plan&id=".$plan->id ) );
                $_cls = ( (++$odd & 1) ? 'odd':'even' );
                echo $this->plan( $plan , array( "class" => " table span-18 last ".$_cls , "edit" =>$_edit ) );
            endforeach;
        ?>
     </div>
</div>