<div id="" class="">
<?php echo $this->title($this->title); ?>
   	<div class='wrapper-content-left-column span-4'>
	   	<div class='add-link link'><a href ='<?php echo $this->url( array ( 'module' => $this->mdl, 'controller' => 'payment', 'action' => 'edit', 'id' => '' ) )?>'>Add</a></div>
	   	<div class='add-link link'><a href ='<?php echo $this->url( array ( 'module' => $this->mdl, 'controller' => 'payment', 'action' => 'index', 'id' => 0 ) )?>'>Back</a></div>
	</div>
	
	
	<div class='wrapper-content-right-column span-19 last'>
		<?php echo $this->message( $this->message );	?>
    	<?php echo "<div class='widget'><div class='head'><h5 class=''>...</h5></div>".( $this->form)."</div>";?>  
   	</div>   
</div>