<div id="" style="margin: auto 0;">	
<?php echo $this->title($this->title); ?>
<div class='h-separator'></div>
<div id="">	
    <?php foreach($this->items as $k => $entry): ?>
     <div class="cms-small-entry-div" id="" style="">
       <div  class="cms-small-entry-title-div" id="" ><?php echo $entry['title']; ?></div>
		<div  class="cms-small-entry-content-div" id="" ><?php echo $entry['content']; ?></div>
        <div  class="cms-small-entry-date-div" id="" ><?php echo $entry['updated']; ?></div>
        <div  class="cms-small-entry-bottom-div" id="" >
			<?php echo "<a href='".$this->url(array('action'=>'edit','id'=>$entry['id']))."'>Edit</a>";?>
			<?php echo "<a href='".$this->url(array('action'=>'delete','id'=>$entry['id']))."'>Delete</a>";?>
			<?php echo "<a href='".$this->url(array('action'=>'view','id'=>$entry['id']))."'>Preview</a>";?>
		</div>
    </div>
	<?php endforeach;?>	
</div>
</div>




