<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>rentis - error handler</title>
</head>
<body>
<?php /** Message: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)*/?>
  <?php if ('development' == APPLICATION_ENV): ?>
	  <div class='error'>
	 	<h2><?php echo $this->message ." :: ".$this->exception->getCode() ?></h2>
	  	<p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>
	  </div>
	  <div class='notice'>
	  	<h3>Stack trace:</h3><pre><?php echo $this->exception->getTraceAsString() ?></pre>
		<h3>Request Parameters:</h3><pre><?php echo var_export($this->request->getParams(), true) ?></pre>  	
	  </div>
  <?php endif ?>

</body>
</html>
