<?php echo $this->doctype();?>
<html>
<head>
<base href="<?php echo BASE_URL;?>" />




<?php echo $this->headMeta();?>
<?php echo $this->headTitle();?>


<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script> 
<link href="/js/fancybox/jquery.fancybox-1.3.1.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/blueprint/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
<link href="/css/blueprint/print.css" media="print" rel="stylesheet" type="text/css" />
<link href="/css/blueprint/ie.css" media="" rel="stylesheet" type="text/css" />
<link rel="stylesheet" media="screen" href="/css/admin.css" />


<!-- followin files are needed to make YUI editor work -->
<!-- Skin CSS file -->
<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.8.2r1/build/assets/skins/sam/skin.css">
<!-- no such links in views, except it extremely needed -->
</head>
<body class="yui-skin-sam admin">
	<!-- container is bluepring specific -->
	<div class='container' id="container">
		<!-- blueprint specific-->
		<!-- start header -->
		<div id="header" class="header span-24 last">
			<div id="logo" class='logo span-24 last'>
				<a href='/app/index/index'><?php echo $this->logo('<h1>Diovax</h1>', array( 'class' => 'widget-logo-index-top span-4'));?>
				</a>
			</div>
			<div id="menu" class="menu span-21">
				<?php echo $this->menu; ?>
			</div>
	    <?php echo " ".$this->welcome( $this->user , array('welcome_class' => 'span-2 last')); ?>
	
</div>
		<!-- end header -->
		<div id="wrapper" class='wrapper span-24 last'>
			<!-- start content -->
			<div id="content" class='content span-3 right'>
				<?php echo $this->subMenu; ?>
			</div>
			<div id="content" class='content span-20 right'>
				<?php echo $this->layout()->content; ?>
			</div>
			<!-- end content -->
		</div>
		<!-- footer -->
		<div id="footer" class="footer span-24 last">
			<?php echo $this->render('_footer.phtml'); ?></div>
		<!-- end of footer -->
		<!-- End of the container -->
	</div>

	
	
	

<script type="text/javascript" src="/js/lib.js"></script>
<script type="text/javascript" src="/js/app.js"></script>
</body>
</html>
