<div>
<?php echo $this->title($this->title); ?>
<div class="wrapper-content-right-column span-4">
    <div class='link'><?php echo "<a href='".$this->url(array('module' => $this->mdl, 'controller' => 'attribute', 'action' => 'index', 'id' => "" ))."'>Back</a>";?></div>
</div>
<div class="wrapper-content-left-column span-19 last">      
<form action='' method='post'> 
    	<?php echo $this->message($this->message );?>
    	<?php       
        if($this->content){
            echo $this->content;
        ?>
    	<br/>
    	<input type='hidden' name='pid' value='<?php echo $this->id;?>' />
    	<input type='submit' id='button'  class='button' value='Delete'/>
        <?php
            }
            else{     }
        ?>
    	<?php echo $this->link_to_attributes; ?>
</form>
</div>
</div>