<div id='' class='span-24 last' >
    <div class="wrapper-content-left-column span-4">
      <?php echo $this->render('property/_menu.phtml');?>
    </div>
	<div class="wrapper-content-right-column span-20 last">
		<?php echo $this->message( $this->message );?>
		<?php if( is_array($this->data) ): ?>
		<?php if( !isset($odd) ) { $odd = 0; } ?>
		<?php foreach($this->data as $k => $_o ): ?>
			<?php echo $this->location ( $_o,  array( 'class' => ' span-18 last '.( (++$odd & 1)? 'odd':'even').'' ) ); ?>
		<?php endforeach;?>
		<?php endif;?>
		<?php $links = ''; if ( $this->show_paged_links ) 	$links = implode ( $this->paged_links, " | ");	echo ( $links )?' Pages '.$links : ''; ?>
	</div>
</div>