<div class='link'><?php echo '<a href=\'/admin/lease/edit\'>Add lease</a>';?></div>
<div class='link'><?php echo '<a href=\'/admin/lease/view/\'>View lease</a>'; ?></div>
<div class='link'><?php echo '<a href=\'/admin/lease/detail/\'>Add Details</a>';?></div>
<div class='link'><?php echo '<a href=\'/admin/lease/video/\'>Add Video</a>';?></div>
<div class='link'><?php echo '<a href=\'/admin/lease/index/\'>Back</a>';?></div>