<div id='' class='span-24 last'>    
<div class="wrapper-content-left-column span-4"><?php echo $this->render('task/_menu.phtml');?></div>    
<div class="wrapper-content-right-column span-20 last">
	<!--there is a need to add the property being treated-->
	
	
	<!-- the header of the table  -->
	<?php if( is_array($this->data) ): ?>
    <?php foreach($this->data as $k => $_o ): ?>
  	<?php if( !isset($odd) ) $odd = 0; ?>   	
  		<?php echo $this->task( $_o, array( 'class' => '', '' => '' ) ); ?>
	<?php endforeach; ?>	
	<?php endif;?>
	<div  class='table-paging-div' >
		<?php 
			$links = '';
			if ( $this->show_paged_links )
				$links = implode ( $this->paged_links, " | ");	
			echo ( $links )?' Pages '.$links : ''; 	
		?>	
	</div>
</div>
</div>
</div>