<div id="" class="product-upload">
   	<?php echo $this->title($this->title); ?>
	<div class="wrapper-content-left-column span-4">
     <?php  echo $this->render('product/_menu.phtml'); ?>
    </div>   

 <div class="wrapper-content-right-column span-10 last">
   	<!-- has been replaced by a view helper  -->
  	<?php echo $this->message( $this->message );	?>
  	<?php echo $this->success_message ? $this->success_message : ""; ?>
   	<?php 
   		try{
   			echo "<div class='widget'><div class='head'><h5 class=''>...</h5></div>".( $this->form)."</div>";
   		}catch (Exception $e ){
   			echo " <div class = 'error' > ".$e->getMessage()."</div>";
   		}
   ?>   
   
<?php if ( $this->product_media ):?>
<div id='product-upload-images-table' class='table-div'> 
	<?php foreach ( $this->product_media as $medium ) :?>
	<div  class='table-row-div'>
			<div class='table-cell-div large-cell'>
				<?php echo '<a href=\''.$this->jx_url.'/'.$medium->id.'\' id=\'id-jxupload-'.$medium->id.'\' class=\'jxupload\' rel=\''.$this->jx_url.'/'.$medium->id.'\'>'.$medium->caption.'</a>'?>
			</div>
			<div class='table-cell-div'>
				<?php 
					if ( $medium->media_value )
					{
						echo '<img src=\'/assets/img/t/'.$medium->media_value.'\' />';
					}
				 ?>
			</div>
			<div class='table-cell-div'>
				<?php if ($medium->displayed):  echo 'Displayed' ; else: echo 'Not Displayed'; endif;?>
			</div>
			<div class='table-cell-div'>
				<?php echo '<a href=\''.$this->url(array('module' => 'admin', 'controller' => 'product', 'action' => 'delmed', 'id' => $medium->id)).'\'>Delete</a>';?>
			</div>
		</div>
		<?php endforeach;?>	
		</div>
	<?php endif;?>   
</div>
</div>