<?php
/**
 * @link http://jasonfurnell.wordpress.com/2010/01/21/megalists-the-make-or-break-ui-display-element/
 */
	
	$_o = ( isset( $this->booking[0] ) && is_array( $this->booking[0] ) ) ?  $this->booking[0] : $this->booking;
	$_o = ( object ) $_o; 
	
	
	
	if( isset($this->address[0]) && is_array( $this->address[0] ) ){ $_adr = (object)$this->address[0]; }
	else{ $_adr = (object)$this->address; }

	if( isset($this->user[0]) && is_array( $this->user[0] ) ) $_cust = (object)$this->user[0];
	else $_cust = (object)$this->user;

	/**property*/
	if( isset( $this->property[0] ) && is_array( $this->property[0] ) ) $_pt = (object)$this->property[0];
	else $_pt = (object)$this->property;

	//
	$_edit = $this->edit(
		array( 
				'Accept' => "/admin/", 
				'Decline' => "/admin/", 
				'Edit' => "/admin/booking/edit/".$_o->id."/?property=".$_pt->id."&user=".$_cust->id
			)
		);
	$_im = ""; $alt = "";
	echo $this->booking( $_o , array( 'user' => $_cust, 'address' => $_adr, 'class' => ''.$alt.' span-19 last', 'strip' => true, 'site' => '', 'location' => '', 'image' => $_im, 'long' => true, 'editing' => $_edit ) );
	
	/**lease*/
	if( $this->lease && is_array($this->lease ) ){
		foreach( $this->lease as $k => $_o ){
			$_o = ( is_array($_o ) ) ? $_o  : $_o; 
			echo $this->lease( $_o , array(  'class' => 'span-19'  ) );
		}
	}
	
	/**payments section*/
	if( $this->payments && is_array($this->payments ) ){
		foreach( $this->payments as $k => $_o ){
			$_o = ( is_array($_o ) ) ? $_o  : $_o; 
			echo $this->payment( $_o , array(  'class' => 'span-19'  ) );
		}
	}
/***/
/**
rentable

Sign out
Henri Ford
Dashboard Customer » Properties » Lease » Tickets Message Analytics »
Array
(

)
Array
(
    [0] => Array
        (
            [id] => 16
            [name] => Herbert Andrew
            [email] => auser@usr.com
            [birthday] => 0000-00-00 00:00:00
            [category] => admin
            [banned] => 0
            [active] => 1
            [modified] => 0000-00-00 00:00:00
            [created] => 0000-00-00 00:00:00
            [token] => 
        )

)
Array
(
    [0] => Array
        (
            [id] => 5
            [user_id] => 16
            [property_id] => 1
            [status] => 
            [note] => 
            [checkin] => 2010-12-12 12:00:00
            [checkout] => 2010-12-12 12:00:00
            [modified] => 2011-03-08 08:33:29
        )

)
Array
(
    [0] => Array
        (
            [id] => 11
            [booking_id] => 5
            [key] => address
            [value] => 213 Check Address, heroes are feck
            [owner] => 
            [modified] => 2011-03-08 08:33:29
        )

)
	
	
	
	//the media
			 if( is_array( $this->media ) ){
				$this->media = is_array( $this->media[0] ) ? $this->media[0] : $this->media;
				$this->media = ( object ) $this->media;
			}
			$_im = is_object ( $this->media ) ? '/assets/img/t/'.$this->media->media_value : '/assets/img/gallery.png';
			if( is_array( $_im ) ) $_im = $_im[0]['media_value'];
        ?>
		<?php foreach($this->data as $k => $_o ): ?>
			<?php 
				$_o = is_array($_o) ? (object)$_o : $_o; 
				$_edit = $this->edit( array( 'Details' => "/admin/booking/edit/".$_o->booking->id."/?property=".$this->property->id."&user=".$_o->user->id, 'Reject' => "/admin/booking/reject/".$_o->booking->id."" ) );
			?>
		    <?php echo $this->booking( $_o->booking , array( 'class' => 'span-18 last', 'user' => $_o->user , 'image' => $_im , 'property' => $this->property , 'details' => $_o->details, 'editing' => $_edit  ) ); ?>
        
	*/
?>